Repository omisego/ewallet, pull requests merged in 2018-06, with the labels that each got.

#209 Add warnings_as_errors flag to Mixfile
  apps/admin_api/mix.exs
  apps/admin_panel/mix.exs
  apps/ewallet/lib/ewallet/web/v1/serializers/category_serializer.ex
  apps/ewallet/mix.exs
  apps/ewallet_api/mix.exs
  apps/ewallet_db/mix.exs
  apps/local_ledger/mix.exs
  apps/local_ledger_db/mix.exs
  apps/url_dispatcher/mix.exs
Labels: enhancement :rocket:

#219 Surround Transfer retrieval after insert with transaction
  apps/ewallet_db/lib/ewallet_db/transfer.ex
Labels: bug :warning:

#234 Ensure processes started in tests are properly terminated
  apps/ewallet/test/ewallet/fetchers/transaction_consumption_fetcher_test.exs
  apps/ewallet/test/ewallet/gates/transaction_consumption_confirmer_gate_test.exs
  apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
  apps/ewallet/test/ewallet/schedulers/transaction_consumption_scheduler_test.exs
  apps/ewallet/test/ewallet/validators/transaction_consumption_validator_test.exs
  apps/ewallet/test/ewallet/web/v1/event_handlers/event_test.exs
  apps/ewallet/test/ewallet/web/v1/event_handlers/transaction_consumption_confirmation_event_test.exs
Labels: bug :warning:

#236 Check that local_ledger is not nil before loading it with Cloak
  apps/ewallet_db/priv/repo/migrations/20180607103719_move_ledger_response_into_specific_fields.exs
Labels: bug :warning:

#231 Mints for token and total_supply
  apps/admin_api/lib/admin_api/v1/controllers/mint_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/token_controller.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/lib/admin_api/v1/views/mint_view.ex
  apps/admin_api/lib/admin_api/v1/views/token_view.ex
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/mint_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/token_controller_test.exs
  apps/ewallet/lib/ewallet/gates/mint_gate.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/mint_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/token_stats_serializer.ex
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/account.ex
  apps/ewallet_db/lib/ewallet_db/mint.ex
  apps/ewallet_db/lib/ewallet_db/types/integer.ex
Labels: enhancement :rocket:

#239 Fix `Account.put_categories/3` to support both atom and string attribute keys
  apps/admin_api/test/admin_api/v1/controllers/account_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/account.ex
Labels: bug :warning:

#244 /category.update to support updating account_ids
  apps/admin_api/test/admin_api/v1/controllers/category_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/account.ex
  apps/ewallet_db/lib/ewallet_db/category.ex
  apps/ewallet_db/lib/ewallet_db/helpers/input_attribute.ex
  apps/ewallet_db/test/ewallet_db/account_test.exs
  apps/ewallet_db/test/ewallet_db/category_test.exs
  apps/ewallet_db/test/ewallet_db/helpers/input_attribute_test.exs
Labels: enhancement :rocket:, work in progress :construction:

#246 Move idempotency token to body
  apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transaction_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transfer_controller.ex
  apps/admin_api/lib/admin_api/v1/plugs/idempotency.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/transfer_controller_test.exs
  apps/admin_api/test/support/conn_case.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_consumption_controller.ex
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transfer_controller.ex
  apps/ewallet_api/lib/ewallet_api/v1/plugs/idempotency.ex
  apps/ewallet_api/lib/ewallet_api/v1/router.ex
  apps/ewallet_api/priv/spec.yaml
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_consumption_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
  apps/ewallet_api/test/support/conn_case.ex
Labels: enhancement :rocket:

#241 Update README with build requirements & Gitter
  .github/CONTRIBUTING.md
  README.md
Labels: enhancement :rocket:

#247 Fix transaction calculation fail
  apps/local_ledger_db/lib/local_ledger_db/transaction.ex
  apps/local_ledger_db/test/local_ledger_db/transaction_test.exs
Labels: bug :warning:

#252 user detail page
  apps/admin_panel/assets/package.json
  apps/admin_panel/assets/src/app/routes/index.js
  apps/admin_panel/assets/src/omg-app-layout/SideNavigation.js
  apps/admin_panel/assets/src/omg-page-transaction/index.js
  apps/admin_panel/assets/src/omg-page-user-detail/index.js
  apps/admin_panel/assets/src/omg-page-users/index.js
  apps/admin_panel/assets/src/omg-page-wallet-detail/index.js
  apps/admin_panel/assets/src/omg-users/action.js
  apps/admin_panel/assets/src/omg-users/reducer.js
  apps/admin_panel/assets/src/omg-users/selector.js
  apps/admin_panel/assets/src/omg-users/userProvider.js
  apps/admin_panel/assets/src/omg-wallet/action.js
  apps/admin_panel/assets/src/omg-wallet/reducer.js
  apps/admin_panel/assets/src/omg-wallet/selector.js
  apps/admin_panel/assets/src/omg-wallet/walletsProvider.js
  apps/admin_panel/assets/src/services/walletService.js
  apps/admin_panel/assets/yarn.lock
Labels: enhancement :rocket:

#254 Fix channels in Admin/Client API
  apps/admin_api/lib/admin_api/v1/channels/account_channel.ex
  apps/admin_api/lib/admin_api/v1/channels/transaction_consumption_channel.ex
  apps/admin_api/lib/admin_api/v1/channels/transaction_request_channel.ex
  apps/admin_api/lib/admin_api/v1/channels/user_channel.ex
  apps/admin_api/lib/admin_api/v1/channels/wallet_channel.ex
  apps/admin_api/test/admin_api/v1/channels/account_channel_test.exs
  apps/admin_api/test/admin_api/v1/channels/address_channel_test.exs
  apps/admin_api/test/admin_api/v1/channels/transaction_consumption_channel_test.exs
  apps/admin_api/test/admin_api/v1/channels/transaction_request_channel_test.exs
  apps/admin_api/test/admin_api/v1/channels/user_channel_test.exs
  apps/ewallet_api/lib/ewallet_api/v1/channels/account_channel.ex
  apps/ewallet_api/lib/ewallet_api/v1/channels/transaction_consumption_channel.ex
  apps/ewallet_api/lib/ewallet_api/v1/channels/transaction_request_channel.ex
  apps/ewallet_api/lib/ewallet_api/v1/channels/user_channel.ex
  apps/ewallet_api/lib/ewallet_api/v1/channels/wallet_channel.ex
  apps/ewallet_api/lib/ewallet_api/v1/sockets/socket.ex
  apps/ewallet_api/test/ewallet_api/v1/channels/account_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/address_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/transaction_consumption_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/transaction_request_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/user_channel_test.exs
Labels: bug :warning:

#259 Allow transaction_request to be created with only token_id and type
  apps/ewallet/lib/ewallet/gates/transaction_request_gate.ex
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
Labels: bug :warning:

#260 Remove token from Wallet
  apps/ewallet_db/lib/ewallet_db/wallet.ex
  apps/ewallet_db/priv/repo/migrations/20180620100944_remove_token_uuid_from_wallets.exs
  apps/ewallet_db/test/support/factory.ex
Labels: Refactor :gear:

#256 Update mint refine, format number
  apps/admin_panel/assets/src/omg-alert/index.js
  apps/admin_panel/assets/src/omg-alert/reducer.js
  apps/admin_panel/assets/src/omg-create-transaction-modal/index.js
  apps/admin_panel/assets/src/omg-mint-token-modal/index.js
  apps/admin_panel/assets/src/omg-page-token-detail/index.js
  apps/admin_panel/assets/src/omg-page-transaction/index.js
  apps/admin_panel/assets/src/omg-page-user-detail/index.js
  apps/admin_panel/assets/src/omg-page-wallet-detail/index.js
  apps/admin_panel/assets/src/omg-transaction/action.js
  apps/admin_panel/assets/src/omg-wallet/walletsProvider.js
  apps/admin_panel/assets/src/services/transactionService.js
Labels: enhancement :rocket:

#261 Fix consumptions unneeded params
  apps/ewallet/lib/ewallet/gates/transaction_consumption_consumer_gate.ex
  apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
  apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_consumption_controller_test.exs
Labels: bug :warning:

#265 Allow API keys to be disabled/enabled
  apps/admin_api/lib/admin_api/v1/controllers/api_key_controller.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/api_key_controller_test.exs
  apps/admin_api/test/admin_api/v1/views/api_key_view_test.exs
  apps/ewallet/lib/ewallet/web/v1/serializers/api_key_serializer.ex
  apps/ewallet_db/lib/ewallet_db/api_key.ex
Labels: enhancement :rocket:

#270 Improve amounts displayed in insufficient funds error
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transfer_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transfer_controller_test.exs
  apps/ewallet/lib/ewallet/formatters/amount_formatter.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/test/ewallet/formatters/amount_formatter_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
Labels: enhancement :rocket:

#271 Rename constraint names to align with latest table schemas
  apps/ewallet_db/priv/repo/migrations/20180626055050_update_constraint_names.exs
Labels: bug :warning:

#273 Update address format to align with OIP-3
  apps/admin_api/test/admin_api/v1/channels/address_channel_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_request_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transfer_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/wallet_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_request_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transfer_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/wallet_controller_test.exs
  apps/ewallet/test/ewallet/fetchers/address_record_fetcher_test.exs
  apps/ewallet/test/ewallet/fetchers/wallet_credit_debit_assigner_test.exs
  apps/ewallet/test/ewallet/fetchers/wallet_fetcher_test.exs
  apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
  apps/ewallet/test/ewallet/gates/transaction_request_gate_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/address_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/types/wallet_address.ex
  apps/ewallet_db/lib/ewallet_db/wallet.ex
  apps/ewallet_db/priv/repo/migrations/20180627073155_update_genesis_address_in_wallet.exs
  apps/ewallet_db/test/ewallet_db/types/wallet_address_test.exs
  apps/ewallet_db/test/ewallet_db/wallet_test.exs
  apps/ewallet_db/test/support/factory.ex
  apps/local_ledger_db/mix.exs
  apps/local_ledger_db/priv/repo/migrations/20180627100553_update_genesis_address_in_wallet.exs
Labels: enhancement :rocket:

#280 Fix Token ID generation should generate the ULID part in lower case
  apps/ewallet_db/lib/ewallet_db/token.ex
  apps/ewallet_db/priv/repo/migrations/20180627115719_update_token_id_to_lowercase.exs
  apps/ewallet_db/test/ewallet_db/token_test.exs
  apps/local_ledger_db/priv/repo/migrations/20180627122112_update_id_to_lowercase_in_token.exs
Labels: bug :warning:

#283 Add token.update endpoint
  apps/admin_api/lib/admin_api/v1/controllers/token_controller.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/token_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/token_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/token.ex
  apps/ewallet_db/test/ewallet_db/token_test.exs
Labels: enhancement :rocket:

#284 Fix error 500 when password input is too short
  apps/admin_api/lib/admin_api/v1/controllers/invite_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/reset_password_controller.ex
  apps/admin_api/lib/admin_api/v1/views/reset_password_view.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/invite_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/reset_password_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/invite.ex
Labels: bug :warning:

#285 Prevents category deletion if accounts are still associated
  apps/admin_api/lib/admin_api/v1/controllers/category_controller.ex
  apps/admin_api/lib/admin_api/v1/error_handler.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/category_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/category_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/category.ex
  apps/ewallet_db/test/ewallet_db/category_test.exs
Labels: bug :warning:

#289 Fix errors from asserting a non-deterministic list position
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/wallet_controller_test.exs
Labels: bug :warning:
