Repository omisego/ewallet, pull requests merged in 2018-08, with the labels that each got.

#387 Remove vagrant setup from readme temporarily
  README.md
Labels: kind/bug :warning:, s3/review

#397 Fix error description not converting field names from _uuid to _id
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/exchange_pair_controller_test.exs
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
Labels: kind/bug :warning:, p1/normal, s3/review

#404 Switch user_id to id for /user.get_transaction_consumptions
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
  apps/ewallet/lib/ewallet/fetchers/user_fetcher.ex
Labels: kind/bug :warning:, s3/review

#398 Enable transaction request exchange functionality.
  apps/admin_panel/assets/package.json
  apps/admin_panel/assets/src/omg-cache/selector.js
  apps/admin_panel/assets/src/omg-consumption-panel/index.js
  apps/admin_panel/assets/src/omg-create-token-modal/index.js
  apps/admin_panel/assets/src/omg-create-transaction-modal/index.js
  apps/admin_panel/assets/src/omg-create-transaction-request-modal/index.js
  apps/admin_panel/assets/src/omg-exchange-rate-modal/index.js
  apps/admin_panel/assets/src/omg-links/index.js
  apps/admin_panel/assets/src/omg-mint-token-modal/index.js
  apps/admin_panel/assets/src/omg-page-account/index.js
  apps/admin_panel/assets/src/omg-page-transaction-request/index.js
  apps/admin_panel/assets/src/omg-token-select/index.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/ConsumeBox.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/PropertiesTab.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/TransactionRequestDetail.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/index.js
  apps/admin_panel/assets/src/omg-transaction-request/action.js
  apps/admin_panel/assets/src/omg-transaction/action.js
  apps/admin_panel/assets/src/omg-transaction/action.test.js
  apps/admin_panel/assets/src/omg-uikit/button/default.js
  apps/admin_panel/assets/src/omg-uikit/button/index.js
  apps/admin_panel/assets/src/omg-uikit/button/primary.js
  apps/admin_panel/assets/src/omg-uikit/input/index.js
  apps/admin_panel/assets/src/omg-uikit/loading/index.js
  apps/admin_panel/assets/src/omg-uikit/select/index.js
  apps/admin_panel/assets/src/omg-uikit/table/index.js
  apps/admin_panel/assets/src/omg-user-current/currentUserProvider.js
  apps/admin_panel/assets/src/services/transactionRequestService.js
  apps/admin_panel/assets/src/services/transactionService.js
  apps/admin_panel/assets/src/utils/createFetcher.js
  apps/admin_panel/assets/src/utils/formatter.js
  apps/admin_panel/assets/src/utils/formatter.test.js
  apps/admin_panel/assets/src/utils/search.js
  apps/admin_panel/assets/statics/images/GO-DeepBlue-White.gif
  apps/admin_panel/assets/webpack/GO-DeepBlue-White.gif
  apps/admin_panel/assets/yarn.lock
Labels: kind/bug :warning:, kind/enhancement :rocket:, p0/high, s3/review

#400 Add syncing exchange pair
  apps/admin_panel/assets/src/omg-exchange-pair/action.js
  apps/admin_panel/assets/src/omg-exchange-rate-modal/index.js
  apps/admin_panel/assets/src/services/exchangePairService.js
Labels: kind/enhancement :rocket:, p1/normal, s3/review

#417 Properly handle invalid amounts for consumption
  apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
  apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
Labels: s2/wip :construction:

#423 Fix log error for websocket
  apps/admin_panel/assets/src/socket/connector.js
Labels: s3/review

#405 Added port mapping 4000:4000 to docker installation instructions
  docs/setup/docker.md
Labels: s3/review

#415 Change coding conventions link to proper route
  .github/CONTRIBUTING.md
Labels: s3/review

#426 Fix unencoded email invite url
  apps/admin_api/lib/admin_api/emails/forget_password_email.ex
  apps/admin_api/lib/admin_api/invites/invite_email.ex
  apps/admin_api/test/admin_api/emails/forget_password_email_test.exs
  apps/admin_api/test/admin_api/invites/invite_email_test.exs
Labels: s2/wip :construction:

#428 Handle edge case for avatar component
  apps/admin_panel/assets/src/omg-uikit/avatar/index.js
  apps/admin_panel/assets/src/omg-wallet-select/index.js
Labels: kind/bug :warning:, s2/wip :construction:

#424 strict dialyzer analysis
  apps/ewallet/lib/ewallet/fetchers/transaction_consumption_fetcher.ex
  apps/ewallet/lib/ewallet/gates/transaction_consumption_confirmer_gate.ex
  apps/ewallet/lib/ewallet/gates/transaction_consumption_consumer_gate.ex
  mix.exs
Labels: kind/enhancement :rocket:, p1/normal, s2/wip :construction:

#438 Add common troubleshooting guide
  README.md
  docs/setup/bare_metal.md
  docs/setup/docker.md
  docs/setup/troubleshooting.md
  docs/setup/vagrant.md
Labels: s2/wip :construction:

#444 Fix Elixir 1.7.0 warnings
  apps/admin_api/mix.exs
  apps/admin_panel/mix.exs
  apps/ewallet/mix.exs
  apps/ewallet_api/mix.exs
  apps/ewallet_db/mix.exs
  apps/local_ledger/mix.exs
  apps/local_ledger_db/mix.exs
  apps/url_dispatcher/mix.exs
Labels: kind/enhancement :rocket:, s2/wip :construction:
