Repository omisego/ewallet, pull requests merged in 2018-10, with the labels that each got.

#440 Composable filters as request params
  apps/admin_api/lib/admin_api/v1/controllers/transaction_controller.ex
  apps/admin_api/priv/spec.json
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_controller_test.exs
  apps/ewallet/lib/ewallet/web/match_all_parser.ex
  apps/ewallet/lib/ewallet/web/match_any_parser.ex
  apps/ewallet/lib/ewallet/web/match_any_parser_helper.ex
  apps/ewallet/lib/ewallet/web/search_parser.ex
  apps/ewallet/test/ewallet/web/match_all_parser_test.exs
  apps/ewallet/test/ewallet/web/match_any_parser_test.exs
  docs/guides/advanced_filtering.md
  docs/guides/guides.md
Labels: kind/enhancement :rocket:, s3/review :eyes:

#480 Fix EWallet tests' dependency on AdminAPI and EWalletAPI module
  apps/ewallet/test/ewallet/web/inviter_test.exs
  apps/ewallet/test/support/mock_invite_email.ex
Labels: s3/review :eyes:

#475 Streamline docker setup guide
  docs/setup/docker.md
Labels: kind/enhancement :rocket:, p1/normal, s3/review :eyes:

#479 Add full_name and calling_name to user
  apps/admin_api/priv/spec.json
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_membership_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/invite_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/user_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/account_membership_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/user_controller_test.exs
  apps/admin_api/test/admin_api/v1/serializers/membership_serializer_test.exs
  apps/admin_api/test/admin_api/v1/views/self_view_test.exs
  apps/admin_api/test/admin_api/v1/views/user_view_test.exs
  apps/ewallet/lib/ewallet/web/v1/serializers/user_serializer.ex
  apps/ewallet/test/ewallet/web/v1/serializers/user_serializer_test.exs
  apps/ewallet_api/priv/spec.json
  apps/ewallet_api/priv/spec.yaml
  apps/ewallet_api/test/ewallet_api/v1/controllers/self_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/views/self_view_test.exs
  apps/ewallet_api/test/ewallet_api/v1/views/user_view_test.exs
  apps/ewallet_db/lib/ewallet_db/user.ex
  apps/ewallet_db/priv/repo/migrations/20181001065043_add_full_name_and_calling_name_to_user.exs
  apps/ewallet_db/test/ewallet_db/user_test.exs
  apps/ewallet_db/test/support/factory.ex
Labels: s3/review :eyes:

#483 Isolate admin password update functionality
  apps/admin_api/lib/admin_api/v1/controllers/invite_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/reset_password_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/self_controller.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/priv/spec.json
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/admin_auth_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/invite_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/self_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/self_controller_test.exs
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet_api/test/ewallet_api/v1/controllers/auth_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/invite.ex
  apps/ewallet_db/lib/ewallet_db/user.ex
  apps/ewallet_db/priv/repo/seeds/01_user.exs
  apps/ewallet_db/priv/repo/seeds_sample/00_admin_panel_user.exs
  apps/ewallet_db/priv/repo/seeds_sample/00_user.exs
  apps/ewallet_db/priv/repo/seeds_test/01_user.exs
  apps/ewallet_db/test/ewallet_db/audit_test.exs
  apps/ewallet_db/test/ewallet_db/invite_test.exs
  apps/ewallet_db/test/ewallet_db/user_test.exs
Labels: s3/review :eyes:

#488 Fix error when running test seed without ENV
  apps/ewallet/lib/mix/tasks/omg.seed.ex
Labels: s2/wip :construction:

#492 Prevent 500 when sending same correlation ID with consumptions
  apps/ewallet_db/priv/repo/migrations/20181008085802_rename_unicity_constraint_for_consumption_correlation_id.exs
  apps/ewallet_db/test/ewallet_db/transaction_consumption_test.exs
Labels: kind/bug :warning:, s3/review :eyes:

#495 Add update password feature
  apps/admin_panel/assets/src/omg-account-current/reducer.js
  apps/admin_panel/assets/src/omg-alert/reducer.js
  apps/admin_panel/assets/src/omg-create-account-modal/index.js
  apps/admin_panel/assets/src/omg-createNewPassword-form/index.js
  apps/admin_panel/assets/src/omg-forgetPassword-form/index.js
  apps/admin_panel/assets/src/omg-login-form/index.js
  apps/admin_panel/assets/src/omg-page-user-setting/index.js
  apps/admin_panel/assets/src/omg-session/action.js
  apps/admin_panel/assets/src/omg-session/action.test.js
  apps/admin_panel/assets/src/omg-user-current/reducer.js
  apps/admin_panel/assets/src/services/sessionService.js
Labels: kind/enhancement :rocket:, p0/high

#497 Preload exchange pair in consumptions
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
  apps/ewallet/lib/ewallet/web/v1/overlays/transaction_consumption_overlay.ex
Labels: s3/review :eyes:
