Repository omisego/ewallet, pull requests merged in 2018-12, with the labels that each got.

#577 Handle value casting for update properly
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/configuration_controller_test.exs
  apps/ewallet_config/lib/ewallet_config/setting.ex
  apps/ewallet_config/lib/ewallet_config/setting_validator.ex
Labels: s3/review :eyes:

#569 Add version informations in status responses
  apps/admin_api/config/config.exs
  apps/admin_api/lib/admin_api/global/controllers/status_controller.ex
  apps/admin_api/mix.exs
  apps/admin_api/test/admin_api/global/controllers/status_controller_test.exs
  apps/admin_panel/mix.exs
  apps/ewallet/mix.exs
  apps/ewallet_api/config/config.exs
  apps/ewallet_api/lib/ewallet_api/global/controllers/status_controller.ex
  apps/ewallet_api/mix.exs
  apps/ewallet_api/test/ewallet_api/global/controllers/status_controller_test.exs
  apps/ewallet_config/mix.exs
  apps/ewallet_db/mix.exs
  apps/load_tester/mix.exs
  apps/local_ledger/mix.exs
  apps/local_ledger_db/mix.exs
  apps/url_dispatcher/lib/url_dispatcher/plug.ex
  apps/url_dispatcher/mix.exs
  apps/url_dispatcher/test/url_dispatcher/plug_test.exs
  config/config.exs
Labels: s3/review :eyes:

#573 Refactor websocket policies
  apps/admin_api/lib/admin_api/v1/channels/account_channel.ex
  apps/admin_api/lib/admin_api/v1/channels/transaction_consumption_channel.ex
  apps/admin_api/lib/admin_api/v1/channels/transaction_request_channel.ex
  apps/admin_api/lib/admin_api/v1/channels/user_channel.ex
  apps/admin_api/lib/admin_api/v1/channels/wallet_channel.ex
  apps/admin_api/lib/admin_api/v1/controllers/key_controller.ex
  apps/admin_api/test/admin_api/v1/channels/account_channel_test.exs
  apps/admin_api/test/admin_api/v1/channels/address_channel_test.exs
  apps/admin_api/test/admin_api/v1/channels/transaction_consumption_channel_test.exs
  apps/admin_api/test/admin_api/v1/channels/transaction_request_channel_test.exs
  apps/admin_api/test/admin_api/v1/channels/user_channel_test.exs
  apps/admin_api/test/admin_api/v1/channels/wallet_channel_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/key_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/key_controller_test.exs
  apps/admin_api/test/support/channel_case.ex
  apps/ewallet/lib/ewallet/policies/account_policy.ex
  apps/ewallet/lib/ewallet/policies/transaction_consumption_policy.ex
  apps/ewallet/lib/ewallet/policies/transaction_request_policy.ex
  apps/ewallet/lib/ewallet/policies/user_policy.ex
  apps/ewallet/lib/ewallet/policies/wallet_policy.ex
  apps/ewallet_api/lib/ewallet_api/v1/auth/client_auth.ex
  apps/ewallet_api/lib/ewallet_api/v1/channels/transaction_consumption_channel.ex
  apps/ewallet_api/lib/ewallet_api/v1/channels/transaction_request_channel.ex
  apps/ewallet_api/lib/ewallet_api/v1/channels/user_channel.ex
  apps/ewallet_api/lib/ewallet_api/v1/channels/wallet_channel.ex
  apps/ewallet_api/lib/ewallet_api/v1/controllers/self_controller.ex
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_consumption_controller.ex
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_controller.ex
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_request_controller.ex
  apps/ewallet_api/lib/ewallet_api/v1/plugs/client_auth_plug.ex
  apps/ewallet_api/test/ewallet_api/v1/auth/client_auth_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/address_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/transaction_consumption_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/transaction_request_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/user_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/wallet_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/plugs/client_auth_plug_test.exs
  apps/ewallet_api/test/support/channel_case.ex
  apps/ewallet_db/lib/ewallet_db/key.ex
  apps/ewallet_db/test/ewallet_db/key_test.exs
Labels: kind/refactor :gear:, s3/review :eyes:

#578 Add `mix omg.migrate.settings` for migrating settings in the environment variables to database
  apps/ewallet/config/config.exs
  apps/ewallet/lib/mix/tasks/omg.migrate.settings.ex
  apps/url_dispatcher/lib/url_dispatcher/application.ex
  apps/url_dispatcher/mix.exs
Labels: s3/review :eyes:

#589 Clean up Settings documentation & workaround for SMTP_USER env variable
  README.md
  apps/ewallet/config/config.exs
  apps/local_ledger/config/config.exs
  docs/setup/advanced/env.md
  docs/setup/advanced/settings.md
  docs/setup/bare_metal.md
  docs/setup/docker.md
  mix.exs
Labels: s3/review :eyes:

#582 Make users global in admin panel
  apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transaction_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transaction_request_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/wallet_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/wallet_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/wallet_controller_test.exs
  apps/admin_panel/assets/src/services/userService.js
  apps/ewallet_db/lib/ewallet_db/transaction.ex
  apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
  apps/ewallet_db/lib/ewallet_db/transaction_request.ex
Labels: s3/review :eyes:

#585 Report internal server errors to Sentry
  apps/admin_api/config/config.exs
  apps/admin_api/lib/admin_api/endpoint.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/mix.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/status_controller_test.exs
  apps/admin_api/test/test_helper.exs
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/mix.exs
  apps/ewallet/test/ewallet/web/v1/error_handler_test.exs
  apps/ewallet/test/ewallet_test.exs
  apps/ewallet/test/test_helper.exs
  apps/ewallet_api/config/config.exs
  apps/ewallet_api/lib/ewallet_api/endpoint.ex
  apps/ewallet_api/lib/ewallet_api/v1/router.ex
  apps/ewallet_api/mix.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/status_controller_test.exs
  apps/ewallet_api/test/test_helper.exs
  mix.lock
Labels: s3/review :eyes:

#588 Fix wrong link in doc
  docs/guides/entities.md
Labels: s3/review :eyes:

#596 Fix migration index issue
  apps/activity_logger/priv/repo/migrations/20180907173648_add_audit.exs
  apps/activity_logger/priv/repo/migrations/20181129045732_rename_audit_to_activity_log.exs
Labels: kind/bug :warning:, s3/review :eyes:

#593 Make sub-app version explicit
  apps/activity_logger/mix.exs
  apps/admin_api/mix.exs
  apps/admin_panel/mix.exs
  apps/ewallet/mix.exs
  apps/ewallet_api/mix.exs
  apps/ewallet_config/mix.exs
  apps/ewallet_db/mix.exs
  apps/load_tester/mix.exs
  apps/local_ledger/mix.exs
  apps/local_ledger_db/mix.exs
  apps/url_dispatcher/mix.exs
Labels: kind/bug :warning:, s3/review :eyes:

#590 Add configuration policies
  apps/admin_api/lib/admin_api/v1/controllers/configuration_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/configuration_controller_test.exs
  apps/ewallet/lib/ewallet/policies/configuration_policy.ex
Labels: s3/review :eyes:

#597 Stricter Redirect URL prefixes comparison
  apps/ewallet/lib/ewallet/web/url_validator.ex
  apps/ewallet/test/ewallet/web/url_validator_test.exs
Labels: s3/review :eyes:

#586 Add AppSignal support
  apps/admin_api/config/config.exs
  apps/admin_api/lib/admin_api/endpoint.ex
  apps/admin_api/mix.exs
  apps/ewallet_api/config/config.exs
  apps/ewallet_api/lib/ewallet_api/endpoint.ex
  apps/ewallet_db/config/dev.exs
  apps/ewallet_db/config/prod.exs
  apps/local_ledger_db/config/dev.exs
  apps/local_ledger_db/config/prod.exs
  docs/setup/advanced/env.md
  mix.lock
Labels: s3/review :eyes:

#604 Add references to the Point of Sale apps in the readme
  README.md
Labels: s2/wip :construction:

#606 Activity Logs Endpoints
  apps/activity_logger/config/config.exs
  apps/activity_logger/lib/activity_logger.ex
  apps/activity_logger/lib/activity_logger/activity_log.ex
  apps/activity_logger/priv/repo/migrations/20181219072950_add_target_and_originator_identifier_in_activity_log.exs
  apps/activity_logger/test/activity_logger/activity_log_test.exs
  apps/activity_logger/test/support/factory.ex
  apps/admin_api/lib/admin_api/v1/controllers/activity_log_controller.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/lib/admin_api/v1/views/account_membership_view.ex
  apps/admin_api/lib/admin_api/v1/views/activity_log_view.ex
  apps/admin_api/priv/spec.json
  apps/admin_api/priv/spec.yaml
  apps/admin_api/priv/swagger/activity_log/paths.yaml
  apps/admin_api/priv/swagger/activity_log/response_schemas.yaml
  apps/admin_api/priv/swagger/activity_log/responses.yaml
  apps/admin_api/priv/swagger/swagger.yaml
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/activity_log_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/activity_log_controller_test.exs
  apps/admin_api/test/admin_api/v1/views/account_membership_view_test.exs
  apps/admin_api/test/admin_api/v1/views/activity_log_view_test.exs
  apps/ewallet/lib/ewallet/gates/activity_log_gate.ex
  apps/ewallet/lib/ewallet/policies/activity_log_policy.ex
  apps/ewallet/lib/ewallet/web/v1/module_mapper.ex
  apps/ewallet/lib/ewallet/web/v1/overlays/activity_log_overlay.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/activity_log_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/membership_serializer.ex
  apps/ewallet/priv/swagger/activity_log/schemas.yaml
  apps/ewallet/test/ewallet/gates/activity_log_gate_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/activity_log_serializer_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/membership_serializer_test.exs
  apps/ewallet_config/lib/ewallet_config/application.ex
  apps/ewallet_db/lib/ewallet_db/application.ex
  apps/ewallet_db/test/support/factory.ex
Labels: kind/enhancement :rocket:, s3/review :eyes:

#605 CSV export for transactions
  .gitignore
  apps/admin_api/lib/admin_api/v1/controllers/export_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transaction_controller.ex
  apps/admin_api/lib/admin_api/v1/error_handler.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/lib/admin_api/v1/views/export_view.ex
  apps/admin_api/lib/admin_api/v1/views/transaction_view.ex
  apps/admin_api/mix.exs
  apps/admin_api/priv/spec.json
  apps/admin_api/priv/spec.yaml
  apps/admin_api/priv/swagger/export/paths.yaml
  apps/admin_api/priv/swagger/export/request_bodies.yaml
  apps/admin_api/priv/swagger/export/response_schemas.yaml
  apps/admin_api/priv/swagger/export/responses.yaml
  apps/admin_api/priv/swagger/swagger.yaml
  apps/admin_api/priv/swagger/transaction/paths.yaml
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_export_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/export_controller_test.exs
  apps/admin_api/test/support/conn_case.ex
  apps/admin_panel/mix.exs
  apps/ewallet/config/config.exs
  apps/ewallet/lib/ewallet/exchange/exchange.ex
  apps/ewallet/lib/ewallet/exporters/adapters/adapter_helper.ex
  apps/ewallet/lib/ewallet/exporters/adapters/gcs_adapter.ex
  apps/ewallet/lib/ewallet/exporters/adapters/local_adapter.ex
  apps/ewallet/lib/ewallet/exporters/adapters/s3_adapter.ex
  apps/ewallet/lib/ewallet/exporters/csv_exporter.ex
  apps/ewallet/lib/ewallet/exporters/exporter.ex
  apps/ewallet/lib/ewallet/gates/export_gate.ex
  apps/ewallet/lib/ewallet/policies/export_policy.ex
  apps/ewallet/lib/ewallet/policies/transaction_policy.ex
  apps/ewallet/lib/ewallet/web/preloader.ex
  apps/ewallet/lib/ewallet/web/v1/overlays/export_overlay.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/csv/transaction_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/export_serializer.ex
  apps/ewallet/mix.exs
  apps/ewallet/priv/swagger/export/schemas.yaml
  apps/ewallet/priv/swagger/shared/request_bodies.yaml
  apps/ewallet/priv/swagger/shared/schemas.yaml
  apps/ewallet_api/config/config.exs
  apps/ewallet_api/mix.exs
  apps/ewallet_config/lib/ewallet_config/application.ex
  apps/ewallet_config/lib/ewallet_config/storage/local.ex
  apps/ewallet_config/mix.exs
  apps/ewallet_db/lib/ewallet_db/api_key.ex
  apps/ewallet_db/lib/ewallet_db/export.ex
  apps/ewallet_db/lib/ewallet_db/uploaders/file.ex
  apps/ewallet_db/mix.exs
  apps/ewallet_db/priv/repo/migrations/20181217041223_add_exports.exs
  apps/ewallet_db/test/support/factory.ex
  apps/load_tester/README.md
  apps/local_ledger/mix.exs
  apps/local_ledger_db/mix.exs
  apps/url_dispatcher/mix.exs
  apps/utils/lib/helpers/pid_helper.ex
  mix.lock
Labels: s3/review :eyes:

#608 Upgrade appsignal to 1.9.0
  mix.lock
Labels: s3/review :eyes:
