Repository omisego/ewallet, pull requests merged in 2018-05, with the labels that each got.

#170 Add missing prefix to account ID
  apps/ewallet_db/priv/repo/migrations/20180430045654_add_id_prefix_to_account.exs
Labels: bug :warning:

#174 Fix seed's argument error
  apps/ewallet/priv/repo/report_minimum.exs
  apps/ewallet/priv/repo/report_sample.exs
  apps/ewallet/priv/repo/seeders/auth_token.exs
Labels: bug :warning:

#184 Show data schemas on Swagger UI
  apps/ewallet/priv/swagger.html
Labels: enhancement :rocket:

#186 Fixed issue #183
  apps/admin_api/priv/spec.yaml
Labels: bug :warning:

#180 Expired consumption event
  apps/ewallet/config/dev.exs
  apps/ewallet/config/prod.exs
  apps/ewallet/lib/ewallet/application.ex
  apps/ewallet/lib/ewallet/scheduler.ex
  apps/ewallet/lib/ewallet/schedulers/transaction_consumption_scheduler.ex
  apps/ewallet/lib/ewallet/schedulers/transaction_request_scheduler.ex
  apps/ewallet/mix.exs
  apps/ewallet/test/ewallet/schedulers/transaction_consumption_scheduler_test.exs
  apps/ewallet/test/ewallet/schedulers/transaction_request_scheduler_test.exs
  apps/ewallet/test/ewallet/web/v1/event_handlers/transaction_consumption_confirmation_event_test.exs
  apps/ewallet_db/config/dev.exs
  apps/ewallet_db/config/prod.exs
  apps/ewallet_db/lib/ewallet_db/application.ex
  apps/ewallet_db/lib/ewallet_db/scheduler.ex
  apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
  apps/ewallet_db/mix.exs
Labels: enhancement :rocket:

#181 Add DB schemas
  README.md
  docs/design/databases.md
  docs/images/ewallet_11052018.png
  docs/images/ewallet_25042018.png
  docs/images/local_ledger_11052018.png
  docs/images/local_ledger_25042018.png
Labels: enhancement :rocket:

#182 Websocket and transaction request flow docs
  docs/guides/transaction_request_flow.md
  docs/websockets/ewallet_api.md
Labels: enhancement :rocket:

#185 Add max_consumption_per_user for transaction requests
  apps/ewallet/lib/ewallet/gates/transaction_consumption_gate.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_request_serializer.ex
  apps/ewallet/test/ewallet/gates/transaction_consumption_gate_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/transaction_request_serializer_test.exs
  apps/ewallet_api/priv/spec.yaml
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
  apps/ewallet_db/lib/ewallet_db/transaction_request.ex
  apps/ewallet_db/priv/repo/migrations/20180511045020_add_max_consumptions_per_user_to_transaction_requests.exs
Labels: enhancement :rocket:

#178 Fix minted token's association with master account
  apps/admin_api/lib/admin_api/v1/controllers/minted_token_controller.ex
Labels: bug :warning:

#172 Fix inconsistent minted token IDs between local ledger and ewallet
  apps/ewallet_db/priv/repo/migrations/20180430105218_update_predictable_minted_token_id.exs
  apps/local_ledger_db/priv/repo/migrations/20180430105449_update_predictable_minted_token_id.exs
Labels: bug :warning:

#179 Improvements to ClientAuthPlug and UserAuthPlug
  apps/admin_api/config/test.exs
  apps/admin_api/lib/admin_api/v1/plugs/client_auth_plug.ex
  apps/admin_api/lib/admin_api/v1/plugs/user_auth_plug.ex
  apps/admin_api/test/admin_api/v1/controllers/auth_controller_test.exs
  apps/admin_api/test/admin_api/v1/plugs/client_auth_plug_test.exs
  apps/admin_api/test/admin_api/v1/plugs/user_auth_plug_test.exs
  apps/admin_api/test/support/conn_case.ex
Labels: bug :warning:

#191 Move AdminPanel front-end build target to /priv/static
  apps/admin_panel/.gitignore
  apps/admin_panel/assets/config/webpack.js
  apps/admin_panel/config/config.exs
  apps/admin_panel/lib/admin_panel/endpoint.ex
  apps/admin_panel/test/admin_panel/test_assets/dist/index.html
Labels: enhancement :rocket:

#190 Cleanup Consumption and handle idempotency
  apps/ewallet/config/dev.exs
  apps/ewallet/config/prod.exs
  apps/ewallet/lib/ewallet/fetchers/transaction_consumption_fetcher.ex
  apps/ewallet/lib/ewallet/fetchers/transaction_request_fetcher.ex
  apps/ewallet/lib/ewallet/gates/transaction_consumption_confirmer_gate.ex
  apps/ewallet/lib/ewallet/gates/transaction_consumption_consumer_gate.ex
  apps/ewallet/lib/ewallet/gates/transaction_consumption_gate.ex
  apps/ewallet/lib/ewallet/gates/transaction_request_gate.ex
  apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
  apps/ewallet/lib/ewallet/web/v1/event_handlers/event.ex
  apps/ewallet/test/ewallet/fetchers/transaction_consumption_fetcher_test.exs
  apps/ewallet/test/ewallet/fetchers/transaction_request_fetcher_test.exs
  apps/ewallet/test/ewallet/gates/transaction_consumption_confirmer_gate_test.exs
  apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
  apps/ewallet/test/ewallet/gates/transaction_request_gate_test.exs
  apps/ewallet/test/ewallet/validators/transaction_consumption_validator_test.exs
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_consumption_controller.ex
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_request_controller.ex
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_consumption_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
  apps/ewallet_db/lib/ewallet_db/transaction_request.ex
  apps/ewallet_db/lib/ewallet_db/transfer.ex
Labels: Refactor :gear:

#198 Update local ledger migration to run with non-superuser permission
  apps/local_ledger_db/priv/repo/migrations/20180430105449_update_predictable_minted_token_id.exs
Labels: bug :warning:

#199 Fix failed logging of consumption errors
  apps/ewallet/lib/ewallet/web/v1/event_handlers/event.ex
  apps/ewallet/test/ewallet/web/v1/event_handlers/event_test.exs
Labels: bug :warning:

#195 T278 me.transfer
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transfer_controller.ex
  apps/ewallet_api/lib/ewallet_api/v1/router.ex
  apps/ewallet_api/priv/spec.yaml
  apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
Labels: enhancement :rocket:

#197 Update BalanceFetcher to return wallets with balances
  apps/ewallet/lib/ewallet/fetchers/balance_fetcher.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/wallet_serializer.ex
  apps/ewallet/test/ewallet/fetchers/balance_fetcher_test.exs
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transfer_controller.ex
  apps/ewallet_api/priv/spec.yaml
  apps/ewallet_api/test/ewallet_api/v1/controllers/self_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/wallet_controller_test.exs
  docs/setup/env.md
Labels: Refactor :gear:

#206 Updating a master account should not return maximum child error
  apps/ewallet_db/lib/ewallet_db/account.ex
  apps/ewallet_db/lib/ewallet_db/account_validator.ex
  apps/ewallet_db/test/ewallet_db/account_test.exs
  apps/ewallet_db/test/ewallet_db/account_validator_test.exs
Labels: bug :warning:

#203 Add Wallet management endpoints to Admin API
  apps/admin_api/lib/admin_api/v1/controllers/wallet_controller.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/lib/admin_api/v1/views/wallet_view.ex
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/wallet_controller_test.exs
  apps/ewallet/lib/ewallet/fetchers/balance_fetcher.ex
  apps/ewallet/lib/ewallet/fetchers/uuid_fetcher.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/wallet_serializer.ex
  apps/ewallet/test/ewallet/fetchers/uuid_fetcher_test.exs
  apps/ewallet_api/priv/spec.yaml
  apps/ewallet_api/test/ewallet_api/v1/controllers/self_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/wallet_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/validator.ex
  apps/ewallet_db/lib/ewallet_db/wallet.ex
  apps/ewallet_db/test/ewallet_db/validator_test.exs
  apps/ewallet_db/test/ewallet_db/wallet_test.exs
  docs/design/wallets.md
  docs/guides/transaction_request_flow.md
Labels: enhancement :rocket:

#213 Fix double quotes in OpenAPI Spec
  apps/admin_api/priv/spec.yaml
Labels: bug :warning:

#215 T17 update credit debit
  apps/ewallet/lib/ewallet/fetchers/credit_debit_record_fetcher.ex
  apps/ewallet/lib/ewallet/fetchers/wallet_credit_debit_assigner.ex
  apps/ewallet/lib/ewallet/fetchers/wallet_fetcher.ex
  apps/ewallet/lib/ewallet/gates/transaction_gate.ex
  apps/ewallet/test/ewallet/fetchers/credit_debit_record_fetcher_test.exs
  apps/ewallet/test/ewallet/fetchers/wallet_credit_debit_assigner_test.exs
  apps/ewallet/test/ewallet/fetchers/wallet_fetcher_test.exs
  apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
  apps/ewallet/test/ewallet/gates/transaction_request_gate_test.exs
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transfer_controller.ex
  apps/ewallet_api/lib/ewallet_api/v1/error_handler.ex
  apps/ewallet_api/priv/spec.yaml
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
Labels: enhancement :rocket:

#214 Prevent random failure for consumption consumer gate
  apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_controller_test.exs
Labels: bug :warning:

#210 Fix API spec not up to date with the changed ID format
  apps/admin_api/priv/spec.yaml
Labels: bug :warning:
