Repository omisego/ewallet, pull requests merged in 2018-09, with the labels that each got.

#443 Allows tokens & wallets to be disabled
  apps/admin_api/lib/admin_api/v1/controllers/token_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/wallet_controller.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/mint_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/token_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_request_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/wallet_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/wallet_controller_test.exs
  apps/admin_api/test/admin_api/v1/views/token_view_test.exs
  apps/ewallet/lib/ewallet/fetchers/token_fetcher.ex
  apps/ewallet/lib/ewallet/fetchers/transaction_source_fetcher.ex
  apps/ewallet/lib/ewallet/gates/mint_gate.ex
  apps/ewallet/lib/ewallet/gates/transaction_request_gate.ex
  apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/token_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/wallet_serializer.ex
  apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
  apps/ewallet/test/ewallet/gates/transaction_gate_test.exs
  apps/ewallet/test/ewallet/gates/transaction_request_gate_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/token_serializer_test.exs
  apps/ewallet_api/priv/spec.yaml
  apps/ewallet_api/test/ewallet_api/v1/controllers/self_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/token.ex
  apps/ewallet_db/lib/ewallet_db/wallet.ex
  apps/ewallet_db/priv/repo/migrations/20180827023828_add_disabled_to_tokens_and_wallets.exs
  apps/ewallet_db/test/ewallet_db/token_test.exs
  apps/ewallet_db/test/support/factory.ex
Labels: kind/enhancement :rocket:

#449 Apply CORSPlug to both AdminAPI and ClientAPI
  apps/admin_api/lib/admin_api/application.ex
  apps/ewallet/lib/ewallet/web/config.ex
  apps/ewallet_api/lib/ewallet_api/application.ex
  apps/ewallet_api/lib/ewallet_api/endpoint.ex
Labels: s2/wip :construction:

#451 Add dependency setup guide via Homebrew
  docs/setup/bare_metal.md
  docs/setup/macos/brew_install_dependencies.md
Labels: kind/enhancement :rocket:, s2/wip :construction:

#454 README improvements following the workshops
  README.md
  assets/provider_setup.jpg
Labels: kind/enhancement :rocket:, p1/normal, s2/wip :construction:

#456 add new image main dash board and fix user endpoint missing page key
  apps/admin_panel/assets/src/omg-page-dashboard/index.js
  apps/admin_panel/assets/src/services/userService.js
  apps/admin_panel/assets/statics/images/Dashboard_Main.png
Labels: kind/bug :warning:, p1/normal, s2/wip :construction:

#461 Preload all required fields for consumptions
  apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
Labels: kind/bug :warning:, s2/wip :construction:

#466 Fix inviting a user failing on the 2nd time
  apps/admin_api/lib/admin_api/v1/controllers/account_membership_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_membership_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/account_membership_controller_test.exs
Labels: kind/bug :warning:, s2/wip :construction:

#471 Fix prefill address bug
  apps/admin_panel/assets/src/omg-create-transaction-modal/index.js
  apps/admin_panel/assets/src/omg-page-users/index.js
Labels: s2/wip :construction:

#473 Fix admin not being able to login after accepting the invitation
  apps/admin_api/lib/admin_api/v1/controllers/invite_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/invite_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/user.ex
  apps/ewallet_db/test/ewallet_db/user_test.exs
Labels: kind/bug :warning:, p1/normal, s2/wip :construction:

#452 Update Docker setup instructions
  docs/setup/docker.md
Labels: kind/enhancement :rocket:, p1/normal, s3/review :eyes:

#457 User tracking/auditing
  apps/admin_api/lib/admin_api/v1/controllers/account_membership_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/reset_password_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/self_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/user_controller.ex
  apps/admin_api/mix.exs
  apps/admin_api/test/admin_api/emails/invite_email_test.exs
  apps/admin_api/test/admin_api/v1/auth/admin_api_auth_test.exs
  apps/admin_api/test/admin_api/v1/auth/admin_user_auth_test.exs
  apps/admin_api/test/admin_api/v1/channels/user_channel_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_membership_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/admin_auth_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/admin_user_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/invite_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/reset_password_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/user_auth_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/user_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/wallet_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/account_membership_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/admin_user_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/user_auth_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/user_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/wallet_controller_test.exs
  apps/admin_api/test/admin_api/v1/serializers/membership_serializer_test.exs
  apps/admin_api/test/admin_api/v1/views/self_view_test.exs
  apps/admin_api/test/admin_api/v1/views/user_view_test.exs
  apps/ewallet/lib/ewallet/web/inviter.ex
  apps/ewallet/lib/ewallet/web/originator.ex
  apps/ewallet/mix.exs
  apps/ewallet/test/ewallet/fetchers/user_fetcher_test.exs
  apps/ewallet/test/ewallet/gates/signup_gate_test.exs
  apps/ewallet/test/ewallet/web/inviter_test.exs
  apps/ewallet_api/mix.exs
  apps/ewallet_api/test/ewallet_api/emails/verification_email_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/auth_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/pages/verify_email_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/signup_controller_test.exs
  apps/ewallet_db/config/config.exs
  apps/ewallet_db/lib/ewallet_db/audit.ex
  apps/ewallet_db/lib/ewallet_db/forget_password_request.ex
  apps/ewallet_db/lib/ewallet_db/invite.ex
  apps/ewallet_db/lib/ewallet_db/structs/system.ex
  apps/ewallet_db/lib/ewallet_db/types/virtual_struct.ex
  apps/ewallet_db/lib/ewallet_db/user.ex
  apps/ewallet_db/priv/repo/migrations/20180907173648_add_audit.exs
  apps/ewallet_db/priv/repo/migrations/20180924092702_add_enabled_to_forget_password_request.exs
  apps/ewallet_db/test/ewallet_db/account_test.exs
  apps/ewallet_db/test/ewallet_db/api_key_test.exs
  apps/ewallet_db/test/ewallet_db/audit_test.exs
  apps/ewallet_db/test/ewallet_db/category_test.exs
  apps/ewallet_db/test/ewallet_db/exchange_pair_test.exs
  apps/ewallet_db/test/ewallet_db/invite_test.exs
  apps/ewallet_db/test/ewallet_db/key_test.exs
  apps/ewallet_db/test/ewallet_db/user_test.exs
  apps/ewallet_db/test/support/factory.ex
  apps/ewallet_db/test/support/schema_case.ex
Labels: kind/enhancement :rocket:, s2/wip :construction:
