Repository omisego/ewallet, pull requests merged in 2018-11, with the labels that each got.

#504 Add match_any filter to Orchestrator
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_controller_test.exs
  apps/ewallet/lib/ewallet/web/orchestrator.ex
  apps/ewallet/test/ewallet/web/orchestrator_test.exs
Labels: kind/bug :warning:, s2/wip :construction:

#506 Fix internal server error when trying to filter a field that's not allowed
  apps/ewallet/lib/ewallet/web/orchestrator.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/test/ewallet/web/orchestrator_test.exs
Labels: s2/wip :construction:

#508 Fix duplicate records after match_all / match_any filter
  apps/ewallet/lib/ewallet/web/filters/match_all_parser.ex
  apps/ewallet/lib/ewallet/web/filters/match_all_query.ex
  apps/ewallet/lib/ewallet/web/filters/match_any_parser.ex
  apps/ewallet/lib/ewallet/web/filters/match_any_query.ex
  apps/ewallet/lib/ewallet/web/filters/match_parser.ex
  apps/ewallet/lib/ewallet/web/match_all_parser.ex
  apps/ewallet/test/ewallet/web/filters/match_all_parser_test.exs
  apps/ewallet/test/ewallet/web/filters/match_any_parser_test.exs
  apps/ewallet/test/ewallet/web/filters/match_parser_test.exs
Labels: s3/review :eyes:

#514 Fix error 500 when trying to filter a disallowed field on /api/admin/account.get_wallets
  apps/ewallet/lib/ewallet/web/orchestrator.ex
  apps/ewallet/lib/ewallet/web/v1/overlays/wallet_overlay.ex
  apps/ewallet/test/ewallet/web/orchestrator_test.exs
Labels: s2/wip :construction:

#516 Add extra tests for MatchAllQuery and MatchAnyQuery
  apps/ewallet/test/ewallet/fetchers/balance_fetcher_test.exs
  apps/ewallet/test/ewallet/web/filters/match_all_query_test.exs
  apps/ewallet/test/ewallet/web/filters/match_any_query_test.exs
Labels: s3/review :eyes:

#522 Fix "only one distinct expression is allowed in query" error
  apps/ewallet/lib/ewallet/web/filters/match_parser.ex
  apps/ewallet/test/ewallet/web/filters/match_parser_test.exs
  apps/ewallet/test/ewallet/web/orchestrator_test.exs
Labels: s3/review :eyes:

#510 Simplify create request design
  apps/admin_panel/assets/.eslintrc.json
  apps/admin_panel/assets/src/omg-create-transaction-request-modal/AdvanceCollapsable.js
  apps/admin_panel/assets/src/omg-create-transaction-request-modal/index.js
  apps/admin_panel/assets/src/omg-page-consumption/index.js
  apps/admin_panel/assets/src/omg-page-transaction-request/index.js
  apps/admin_panel/assets/src/omg-page-transaction/index.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/ConsumeBox.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/TransactionRequestDetail.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/index.js
  apps/admin_panel/assets/src/omg-uikit/table/index.js
  apps/admin_panel/assets/src/services/transactionRequestService.js
Labels: kind/enhancement :rocket:, p1/normal, s3/review :eyes:

#527 Add the insertion of a normal user to the test seed
  apps/ewallet/lib/ewallet/policies/transaction_request_policy.ex
  apps/ewallet_config/config/config.exs
  apps/ewallet_db/priv/repo/seeds_test/01_user.exs
  apps/ewallet_db/priv/repo/seeds_test/10_setting.exs
  docs/setup/advanced/env.md
Labels: kind/enhancement :rocket:, s2/wip :construction:

#532 Always preload tokens in exchange pair when doing /transaction.calculate
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_calculation_controller_test.exs
  apps/ewallet/lib/ewallet/exchange/exchange.ex
Labels: s2/wip :construction:

#512 Improve search for wallets, tokens, users and fix bug error login message
  apps/admin_panel/assets/src/app/bootup/action.js
  apps/admin_panel/assets/src/omg-create-transaction-modal/index.js
  apps/admin_panel/assets/src/omg-create-transaction-request-modal/index.js
  apps/admin_panel/assets/src/omg-exchange-rate-modal/index.js
  apps/admin_panel/assets/src/omg-login-form/index.js
  apps/admin_panel/assets/src/omg-page-account-detail/index.js
  apps/admin_panel/assets/src/omg-page-token-detail/HistoryTable.js
  apps/admin_panel/assets/src/omg-page-token/index.js
  apps/admin_panel/assets/src/omg-page-users/index.js
  apps/admin_panel/assets/src/omg-session/action.js
  apps/admin_panel/assets/src/omg-session/action.test.js
  apps/admin_panel/assets/src/omg-token/action.js
  apps/admin_panel/assets/src/omg-token/action.test.js
  apps/admin_panel/assets/src/omg-token/searchField.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/ConsumeBox.js
  apps/admin_panel/assets/src/omg-uikit/select/index.js
  apps/admin_panel/assets/src/omg-users/action.js
  apps/admin_panel/assets/src/omg-users/searchField.js
  apps/admin_panel/assets/src/omg-wallet/action.js
  apps/admin_panel/assets/src/omg-wallet/action.test.js
  apps/admin_panel/assets/src/omg-wallet/searchField.js
  apps/admin_panel/assets/src/services/tokenService.js
  apps/admin_panel/assets/src/services/userService.js
  apps/admin_panel/assets/src/services/walletService.js
  apps/admin_panel/assets/src/utils/createFetcher.js
  apps/admin_panel/assets/src/utils/localStorage.js
Labels: kind/bug :warning:, kind/enhancement :rocket:, p0/high, s2/wip :construction:

#534 Handle mappings in MatchParser
  apps/ewallet/lib/ewallet/web/filters/match_all_parser.ex
  apps/ewallet/lib/ewallet/web/filters/match_any_parser.ex
  apps/ewallet/lib/ewallet/web/filters/match_parser.ex
  apps/ewallet/lib/ewallet/web/orchestrator.ex
  apps/ewallet/test/ewallet/web/filters/match_all_parser_test.exs
Labels: s3/review :eyes:

#535 Enable/disable api keys
  apps/admin_api/lib/admin_api/v1/controllers/api_key_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/key_controller.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/api_key_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/key_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/api_key_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/key_controller_test.exs
  apps/admin_api/test/admin_api/v1/views/api_key_view_test.exs
  apps/admin_api/test/admin_api/v1/views/key_view_test.exs
  apps/ewallet/lib/ewallet/policies/key_policy.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/api_key_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/key_serializer.ex
  apps/ewallet/test/ewallet/web/v1/serializers/key_serializer_test.exs
  apps/ewallet_db/lib/ewallet_db/api_key.ex
  apps/ewallet_db/lib/ewallet_db/key.ex
  apps/ewallet_db/priv/repo/migrations/20181116023106_rename_expired_to_disabled.exs
  apps/ewallet_db/test/ewallet_db/api_key_test.exs
  apps/ewallet_db/test/ewallet_db/key_test.exs
  apps/ewallet_db/test/support/factory.ex
Labels: s3/review :eyes:

#544 Fix swagger doc
  apps/ewallet_api/priv/spec.json
  apps/ewallet_api/priv/spec.yaml
Labels: s3/review :eyes:

#545 Fix seeder calculating string length with a list function
  apps/ewallet/lib/ewallet/seeders/cli_seeder.ex
Labels: s3/review :eyes:

#546 Remove precision from amount decimals stored in DB
  apps/ewallet_db/priv/repo/migrations/20181120090000_change_big_amount_types.exs
  apps/ewallet_db/priv/repo/reporters/seeds_sample.exs
  apps/local_ledger/test/local_ledger/transaction_test.exs
  apps/local_ledger_db/priv/repo/migrations/20181120084934_change_amount_size.exs
Labels: s3/review :eyes:

#548 Supports nil value filtering
  apps/admin_api/test/support/conn_case.ex
  apps/ewallet/lib/ewallet/web/filters/match_all_query.ex
  apps/ewallet/lib/ewallet/web/filters/match_any_query.ex
  apps/ewallet/lib/ewallet/web/filters/match_parser.ex
  apps/ewallet/lib/ewallet/web/orchestrator.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/test/ewallet/web/filters/match_all_query_test.exs
  apps/ewallet/test/ewallet/web/filters/match_any_query_test.exs
Labels: s3/review :eyes:

#552 Fix /api/admin/account.get_members returning error 500 when filtering
  apps/admin_api/lib/admin_api/v1/controllers/account_membership_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_membership_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/account_membership_controller_test.exs
Labels: s3/review :eyes:

#524 Setting page improvement
  apps/admin_panel/assets/.babelrc
  apps/admin_panel/assets/package.json
  apps/admin_panel/assets/src/app/routes/index.js
  apps/admin_panel/assets/src/omg-access-key/accessKeysFetcher.js
  apps/admin_panel/assets/src/omg-account/selector.js
  apps/admin_panel/assets/src/omg-cache/reducer.js
  apps/admin_panel/assets/src/omg-invite-form/index.js
  apps/admin_panel/assets/src/omg-invite-modal/index.js
  apps/admin_panel/assets/src/omg-invite/action.js
  apps/admin_panel/assets/src/omg-invite/inviteListProvider.js
  apps/admin_panel/assets/src/omg-invite/reducer.js
  apps/admin_panel/assets/src/omg-invite/selector.js
  apps/admin_panel/assets/src/omg-member/MembersFetcher.js
  apps/admin_panel/assets/src/omg-member/action.js
  apps/admin_panel/assets/src/omg-member/action.test.js
  apps/admin_panel/assets/src/omg-member/reducer.js
  apps/admin_panel/assets/src/omg-member/reducer.test.js
  apps/admin_panel/assets/src/omg-member/searchField.js
  apps/admin_panel/assets/src/omg-member/selector.js
  apps/admin_panel/assets/src/omg-page-account-setting/index.js
  apps/admin_panel/assets/src/omg-page-user-setting/index.js
  apps/admin_panel/assets/src/omg-tabs/index.js
  apps/admin_panel/assets/src/omg-user-current/currentUserProvider.js
  apps/admin_panel/assets/src/reducer/index.js
  apps/admin_panel/assets/src/services/accountService.js
  apps/admin_panel/assets/yarn.lock
Labels: kind/enhancement :rocket:, s3/review :eyes:

#556 Ignore empty filters
  apps/ewallet/lib/ewallet/web/filters/match_all_parser.ex
  apps/ewallet/lib/ewallet/web/filters/match_any_parser.ex
  apps/ewallet/test/ewallet/web/filters/match_all_parser_test.exs
  apps/ewallet/test/ewallet/web/filters/match_any_parser_test.exs
Labels: s3/review :eyes:
