Repository omisego/ewallet, pull requests merged in 2018-07, with the labels that each got.

#288 Attempt to fix channel tests failures
  apps/admin_api/test/admin_api/v1/channels/account_channel_test.exs
  apps/admin_api/test/admin_api/v1/channels/address_channel_test.exs
  apps/admin_api/test/admin_api/v1/channels/transaction_consumption_channel_test.exs
  apps/admin_api/test/admin_api/v1/channels/transaction_request_channel_test.exs
  apps/admin_api/test/admin_api/v1/channels/user_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/address_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/transaction_consumption_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/transaction_request_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/user_channel_test.exs
Labels: bug :warning:

#290 Handle exchange in Transaction Request flow
  apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transaction_request_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/wallet_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/views/transaction_view_test.exs
  apps/admin_api/test/support/conn_case.ex
  apps/ewallet/lib/ewallet/fetchers/account_fetcher.ex
  apps/ewallet/lib/ewallet/fetchers/amount_fetcher.ex
  apps/ewallet/lib/ewallet/fetchers/transaction_consumption_fetcher.ex
  apps/ewallet/lib/ewallet/fetchers/transaction_request_fetcher.ex
  apps/ewallet/lib/ewallet/fetchers/transaction_source_fetcher.ex
  apps/ewallet/lib/ewallet/gates/transaction_consumption_confirmer_gate.ex
  apps/ewallet/lib/ewallet/gates/transaction_consumption_consumer_gate.ex
  apps/ewallet/lib/ewallet/gates/transaction_request_gate.ex
  apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/lib/ewallet/web/v1/event_handlers/transaction_consumption_event_handler.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_consumption_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/wallet_serializer.ex
  apps/ewallet/test/ewallet/fetchers/transaction_source_fetcher_test.exs
  apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
  apps/ewallet/test/ewallet/validators/transaction_consumption_validator_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/transaction_consumption_serializer_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/transaction_serializer_test.exs
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_consumption_controller.ex
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_controller.ex
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_request_controller.ex
  apps/ewallet_api/priv/spec.yaml
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_consumption_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/views/transaction_view_test.exs
  apps/ewallet_api/test/support/conn_case.ex
  apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
  apps/ewallet_db/lib/ewallet_db/transaction_request.ex
  apps/ewallet_db/priv/repo/migrations/20180629040426_add_exchange_details_to_transaction_request_consumption.exs
  apps/ewallet_db/priv/repo/migrations/20180629050719_add_failure_reason_to_consumption.exs
  apps/ewallet_db/priv/repo/migrations/20180629062430_add_estimated_amount_to_transaction_request_consumption.exs
  apps/ewallet_db/test/ewallet_db/transaction_consumption_test.exs
  docs/guides/transaction_request_flow.md
Labels: enhancement :rocket:

#294 use unauthenticated request
  apps/admin_panel/assets/src/services/adminService.js
Labels: bug :warning:

#275 Account Authorization
  apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/admin_auth_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/self_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/user_controller.ex
  apps/admin_api/lib/admin_api/v1/error_handler.ex
  apps/admin_api/lib/admin_api/v1/helpers/account_helper.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/admin_auth_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/category_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/account_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/category_controller_test.exs
  apps/ewallet/lib/ewallet/helper.ex
  apps/ewallet/lib/ewallet/policies/account_policy.ex
  apps/ewallet/lib/ewallet/web/search_parser.ex
  apps/ewallet_db/lib/ewallet_db/account.ex
  apps/ewallet_db/lib/ewallet_db/key.ex
  apps/ewallet_db/lib/ewallet_db/membership.ex
  apps/ewallet_db/lib/ewallet_db/membership_checker.ex
  apps/ewallet_db/lib/ewallet_db/role.ex
  apps/ewallet_db/lib/ewallet_db/user.ex
  apps/ewallet_db/priv/repo/migrations/20180627084840_add_priority_to_role.exs
  apps/ewallet_db/test/ewallet_db/account_test.exs
  apps/ewallet_db/test/ewallet_db/membership_test.exs
  apps/ewallet_db/test/support/factory.ex
Labels: enhancement :rocket:

#286 Prevents an exchange rate of 0 or below
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/exchange_pair_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/exchange_pair_controller_test.exs
  apps/ewallet/lib/ewallet/application.ex
  apps/ewallet/lib/ewallet/exchange/exchange.ex
  apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/mix.exs
  apps/ewallet/test/ewallet/exchange/exchange_test.exs
  apps/ewallet/test/ewallet/fetchers/amount_fetcher_test.exs
  apps/ewallet_db/lib/ewallet_db/exchange_pair.ex
  apps/ewallet_db/test/ewallet_db/exchange_pair_test.exs
  mix.exs
Labels: bug :warning:

#293 Allow cross-token transactions from/to exchange wallet
  README.md
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_controller_test.exs
  apps/ewallet/lib/ewallet/formatters/transaction_formatter.ex
  apps/ewallet/test/ewallet/formatters/transaction_formatter_test.exs
  docs/design/transactions_and_entries.md
  mix.exs
Labels: bug :warning:

#300 Fix token stats when token not minted yet
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/token_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/types/integer.ex
Labels: bug :warning:

#302 Implement /transaction.calculate
  apps/admin_api/lib/admin_api/v1/controllers/tranasction_calculation_controller.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/lib/admin_api/v1/views/transaction_calculation_view.ex
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_calculation_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_calculation_controller_test.exs
  apps/admin_api/test/admin_api/v1/views/transaction_calculation_view_test.exs
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_calculation_serializer.ex
  apps/ewallet/test/ewallet/web/v1/serializers/transaction_calculation_serializer_test.exs
Labels: enhancement :rocket:

#303 Switch to SHA2 for secret key hashing
  apps/admin_api/lib/admin_api/invites/inviter.ex
  apps/admin_api/test/admin_api/v1/plugs/admin_api_auth_plug_test.exs
  apps/admin_api/test/support/conn_case.ex
  apps/ewallet_db/lib/ewallet_db/api_key.ex
  apps/ewallet_db/lib/ewallet_db/auth_token.ex
  apps/ewallet_db/lib/ewallet_db/forget_password_request.ex
  apps/ewallet_db/lib/ewallet_db/helpers/crypto.ex
  apps/ewallet_db/lib/ewallet_db/invite.ex
  apps/ewallet_db/lib/ewallet_db/key.ex
  apps/ewallet_db/test/ewallet_db/helpers/crypto_test.exs
  apps/ewallet_db/test/ewallet_db/key_test.exs
  apps/ewallet_db/test/support/factory.ex
Labels: enhancement :rocket:

#291 Allow `create_opposite: true/false` on `/exchange_pair.create`
  apps/admin_api/lib/admin_api/v1/controllers/exchange_pair_controller.ex
  apps/admin_api/lib/admin_api/v1/error_handler.ex
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/exchange_pair_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/wallet_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/exchange_pair_controller_test.exs
  apps/ewallet/lib/ewallet/fetchers/uuid_fetcher.ex
  apps/ewallet/lib/ewallet/gates/exchange_pair_gate.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/exchange_pair_serializer.ex
  apps/ewallet/test/ewallet/gates/exchange_pair_gate_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/exchange_pair_serializer_test.exs
  apps/ewallet_db/lib/ewallet_db/exchange_pair.ex
  apps/ewallet_db/lib/ewallet_db/soft_delete.ex
  apps/ewallet_db/lib/ewallet_db/validator.ex
  apps/ewallet_db/priv/repo/migrations/20180704095243_update_unique_index_on_exchange_pair.exs
  apps/ewallet_db/priv/repo/migrations/20180705182907_drop_name_from_exchange_pair.exs
  apps/ewallet_db/test/ewallet_db/exchange_pair_test.exs
  apps/ewallet_db/test/ewallet_db/validator_test.exs
  apps/ewallet_db/test/support/factory.ex
  apps/ewallet_db/test/support/schema_case.ex
Labels: enhancement :rocket:

#304 Whitelist only BASE_URL for invitation emails
  apps/admin_api/config/config.exs
  apps/admin_api/config/prod.exs
  apps/admin_api/lib/admin_api/invites/inviter.ex
  apps/admin_api/lib/admin_api/v1/controllers/account_membership_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/reset_password_controller.ex
  apps/admin_api/test/admin_api/invites/inviter_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_membership_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/reset_password_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/forget_password_request.ex
Labels: bug :warning:

#308 Add /access_key.update
  apps/admin_api/lib/admin_api/v1/controllers/key_controller.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/api_key_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/key_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/api_key_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/key_controller_test.exs
  apps/admin_api/test/admin_api/v1/views/key_view_test.exs
  apps/ewallet/lib/ewallet/web/v1/serializers/key_serializer.ex
  apps/ewallet/test/ewallet/web/v1/serializers/key_serializer_test.exs
  apps/ewallet_db/lib/ewallet_db/key.ex
  apps/ewallet_db/priv/repo/migrations/20180706054113_add_expired_to_key.exs
  apps/ewallet_db/priv/repo/seeds/01_user.exs
  apps/ewallet_db/priv/repo/seeds_sample/00_admin_panel_user.exs
  apps/ewallet_db/test/ewallet_db/api_key_test.exs
  apps/ewallet_db/test/ewallet_db/key_test.exs
  apps/ewallet_db/test/support/factory.ex
  apps/ewallet_db/test/support/schema_case.ex
Labels: enhancement :rocket:

#310 Fix broken spec.yaml due to invalid type
  apps/admin_api/priv/spec.json
  apps/admin_api/priv/spec.yaml
  apps/ewallet_api/priv/spec.json
  docs/api_specs.md
Labels: bug :warning:

#311 Notify requester when consumption is finalized
  apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
  apps/ewallet/lib/ewallet/web/v1/event_handlers/transaction_consumption_event_handler.ex
  apps/ewallet/test/ewallet/schedulers/transaction_consumption_scheduler_test.exs
  apps/ewallet/test/ewallet/web/v1/event_handlers/transaction_consumption_confirmation_event_test.exs
Labels: enhancement :rocket:

#313 Fix all account.get_ endpoints
  apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transaction_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transaction_request_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/user_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/wallet_controller.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_request_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/user_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/wallet_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_request_controller_test.exs
  apps/admin_panel/assets/src/omg-users/action.js
  apps/admin_panel/assets/src/services/userService.js
  apps/ewallet/lib/ewallet/policies/transaction_policy.ex
  apps/ewallet/lib/ewallet/policies/user_policy.ex
  apps/ewallet_db/lib/ewallet_db/account.ex
  apps/ewallet_db/lib/ewallet_db/transaction.ex
  apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
  apps/ewallet_db/lib/ewallet_db/transaction_request.ex
  apps/ewallet_db/lib/ewallet_db/wallet.ex
Labels: enhancement :rocket:

#314 Update `mix seed` and `mix seed --sample` output
  apps/ewallet_db/priv/repo/reporters/seeds.exs
  apps/ewallet_db/priv/repo/reporters/seeds_sample.exs
  apps/ewallet_db/priv/repo/seeds/02_key.exs
  apps/ewallet_db/priv/repo/seeds_sample/01_auth_token.exs
Labels: enhancement :rocket:

#316 Fix permissions for transaction and requests
  apps/ewallet/lib/ewallet/policies/transaction_consumption_policy.ex
  apps/ewallet/lib/ewallet/policies/transaction_policy.ex
  apps/ewallet/lib/ewallet/policies/transaction_request_policy.ex
  apps/ewallet/lib/ewallet/policies/wallet_policy.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
Labels: bug :warning:

#317 Fix error 500 when from_amount and to_amount are equal on /transaction.create
  apps/admin_api/lib/admin_api/v1/controllers/tranasction_calculation_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_calculation_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_calculation_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/views/transaction_view_test.exs
  apps/ewallet/lib/ewallet/fetchers/amount_fetcher.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_serializer.ex
  apps/ewallet/test/ewallet/fetchers/amount_fetcher_test.exs
  apps/ewallet/test/ewallet/gates/transaction_gate_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/transaction_serializer_test.exs
  apps/ewallet_api/test/ewallet_api/v1/views/transaction_view_test.exs
Labels: bug :warning:, work in progress :construction:

#321 Send events when consuming in client API
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_consumption_controller.ex
Labels: bug :warning:

#323 Update Swagger for /account.get_wallets
  apps/admin_api/priv/spec.yaml
Labels: bug :warning:

#325 New seed: initial user funds, exchange pairs, transaction requests and consumptions
  apps/ewallet_db/lib/ewallet_db/transaction_request.ex
  apps/ewallet_db/priv/repo/seeds/01_user.exs
  apps/ewallet_db/priv/repo/seeds_sample/00_token.exs
  apps/ewallet_db/priv/repo/seeds_sample/00_user.exs
  apps/ewallet_db/priv/repo/seeds_sample/01_exchange_pair.exs
  apps/ewallet_db/priv/repo/seeds_sample/30_transaction_request_and_consumption.exs
  apps/ewallet_db/priv/repo/seeds_test/01_user.exs
  apps/ewallet_db/test/ewallet_db/transaction_request_test.exs
Labels: enhancement :rocket:

#331 Add Access key test / Api key test
  apps/admin_panel/assets/src/omg-access-key/action.js
  apps/admin_panel/assets/src/omg-access-key/action.test.js
  apps/admin_panel/assets/src/omg-access-key/reducer.js
  apps/admin_panel/assets/src/omg-access-key/reducer.test.js
  apps/admin_panel/assets/src/omg-api-keys/action.js
  apps/admin_panel/assets/src/omg-api-keys/action.test.js
  apps/admin_panel/assets/src/omg-api-keys/reducer.js
  apps/admin_panel/assets/src/omg-api-keys/reducer.test.js
  apps/admin_panel/assets/src/omg-cache/reducer.js
  apps/admin_panel/assets/src/omg-page-api/index.js
  apps/admin_panel/assets/src/reducer/index.js
  apps/admin_panel/assets/src/services/accessKeyService.js
Labels: kind/refactor :gear:, p1/normal, s3/review

#337 Add transaction request/consumption test
  apps/admin_panel/assets/src/omg-consumption/action.js
  apps/admin_panel/assets/src/omg-consumption/action.test.js
  apps/admin_panel/assets/src/omg-consumption/reducer.js
  apps/admin_panel/assets/src/omg-consumption/reducer.test.js
  apps/admin_panel/assets/src/omg-transaction-request/action.js
  apps/admin_panel/assets/src/omg-transaction-request/action.test.js
  apps/admin_panel/assets/src/omg-transaction-request/reducer.js
  apps/admin_panel/assets/src/omg-transaction-request/reducer.test.js
Labels: kind/refactor :gear:, p1/normal, s3/review

#333 Move E2E seed's master account value from compile-time to runtime
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/key_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/key_controller_test.exs
  apps/ewallet_db/priv/repo/seeds_test/01_user.exs
Labels: kind/bug :warning:, p1/normal, s3/review

#336 Add user test
  apps/admin_panel/assets/src/omg-invite/action.js
  apps/admin_panel/assets/src/omg-user-current/action.js
  apps/admin_panel/assets/src/omg-user-current/action.test.js
  apps/admin_panel/assets/src/omg-user-current/currentUserProvider.js
  apps/admin_panel/assets/src/omg-user-current/reducer.js
  apps/admin_panel/assets/src/omg-users/action.js
  apps/admin_panel/assets/src/omg-users/action.test.js
  apps/admin_panel/assets/src/omg-users/reducer.js
  apps/admin_panel/assets/src/omg-users/reducer.test.js
  apps/admin_panel/assets/src/services/userService.js
Labels: kind/refactor :gear:, p1/normal, s3/review

#339 Consumption Exchange Proper Support
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_request_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_request_controller_test.exs
  apps/ewallet/lib/ewallet/fetchers/exchange_account_fetcher.ex
  apps/ewallet/lib/ewallet/gates/transaction_consumption_consumer_gate.ex
  apps/ewallet/lib/ewallet/gates/transaction_request_gate.ex
  apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_consumption_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_request_serializer.ex
  apps/ewallet/test/ewallet/web/v1/serializers/transaction_consumption_serializer_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/transaction_request_serializer_test.exs
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_consumption_controller.ex
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_consumption_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/helpers/assoc.ex
  apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
  apps/ewallet_db/priv/repo/migrations/20180717115100_fix_exchange_account_in_consumption.exs
Labels: kind/bug :warning:, p0/high, s3/review

#351 Ensure email and redirect_url are not nil when resetting a password
  apps/admin_api/lib/admin_api/v1/controllers/reset_password_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/reset_password_controller_test.exs
Labels: s3/review

#352 Add fallback for upload_avatar endpoints
  apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/self_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/self_controller_test.exs
Labels: kind/bug :warning:, p0/high, s3/review

#353 Remove token_id_not_found error
  apps/admin_api/lib/admin_api/v1/controllers/mint_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/token_controller.ex
  apps/admin_api/lib/admin_api/v1/error_handler.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/token_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/token_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_request_controller_test.exs
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
Labels: kind/bug :warning:, s3/review

#354 Handle nil email submitted for assign_user endpoint
  apps/admin_api/lib/admin_api/v1/controllers/account_membership_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_membership_controller_test.exs
Labels: p0/high, s3/review

#344 Add enable disable functionality for access key / Refine design
  apps/admin_panel/assets/src/omg-alert/reducer.js
  apps/admin_panel/assets/src/omg-app-layout/AccountItem.js
  apps/admin_panel/assets/src/omg-app-layout/AccountSelectorMenu.js
  apps/admin_panel/assets/src/omg-app-layout/SideNavigation.js
  apps/admin_panel/assets/src/omg-app-layout/TopBar.js
  apps/admin_panel/assets/src/omg-app-layout/index.js
  apps/admin_panel/assets/src/omg-consumption-panel/index.js
  apps/admin_panel/assets/src/omg-create-account-modal/ChooseCategoryStage.js
  apps/admin_panel/assets/src/omg-create-transaction-modal/index.js
  apps/admin_panel/assets/src/omg-exchange-rate-modal/index.js
  apps/admin_panel/assets/src/omg-page-account-setting/index.js
  apps/admin_panel/assets/src/omg-page-account/index.js
  apps/admin_panel/assets/src/omg-page-api/index.js
  apps/admin_panel/assets/src/omg-page-layout/TopNavigation.js
  apps/admin_panel/assets/src/omg-page-transaction/index.js
  apps/admin_panel/assets/src/omg-page-wallet-detail/index.js
  apps/admin_panel/assets/src/omg-page-wallets/index.js
  apps/admin_panel/assets/src/omg-table/index.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/index.js
  apps/admin_panel/assets/src/omg-uikit/avatar/index.js
  apps/admin_panel/assets/src/omg-uikit/button/default.js
  apps/admin_panel/assets/src/omg-uikit/loading/index.js
  apps/admin_panel/assets/src/omg-uikit/select/index.js
  apps/admin_panel/assets/src/omg-uikit/table/index.js
Labels: kind/enhancement :rocket:, kind/refactor :gear:, p1/normal, s3/review

#355 Handle invalid files properly when uploading avatars
  apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/self_controller_test.exs
  apps/admin_api/test/support/assets/file.json
Labels: p0/high, s3/review

#356 Fix minting with nil amount
  apps/admin_api/lib/admin_api/v1/controllers/mint_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/token_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/mint_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/token_controller_test.exs
Labels: kind/bug :warning:, p0/high, s3/review

#343 Switch to use DeferredConfig
  apps/admin_api/config/config.exs
  apps/admin_api/config/prod.exs
  apps/admin_api/lib/admin_api/application.ex
  apps/admin_api/lib/admin_api/config.ex
  apps/admin_api/mix.exs
  apps/ewallet/config/config.exs
  apps/ewallet/lib/ewallet/web/paginator.ex
  apps/ewallet/test/ewallet/web/paginator_test.exs
  apps/ewallet_api/config/config.exs
  apps/ewallet_api/config/prod.exs
  apps/ewallet_api/mix.exs
  apps/ewallet_db/config/adapters/aws.exs
  apps/ewallet_db/config/adapters/gcs.exs
  apps/ewallet_db/config/adapters/local.exs
  apps/ewallet_db/config/config.exs
  apps/ewallet_db/config/dev.exs
  apps/ewallet_db/config/prod.exs
  apps/ewallet_db/config/test.exs
  apps/ewallet_db/lib/ewallet_db/application.ex
  apps/ewallet_db/lib/ewallet_db/config.ex
  apps/ewallet_db/lib/ewallet_db/repo.ex
  apps/local_ledger/config/config.exs
  apps/local_ledger/config/prod.exs
  apps/local_ledger/lib/local_ledger/application.ex
  apps/local_ledger/lib/local_ledger/config.ex
  apps/local_ledger/mix.exs
  apps/local_ledger_db/config/dev.exs
  apps/local_ledger_db/config/prod.exs
  apps/local_ledger_db/config/test.exs
  apps/local_ledger_db/lib/local_ledger_db/application.ex
  apps/local_ledger_db/lib/repo.ex
  apps/local_ledger_db/mix.exs
  apps/url_dispatcher/config/config.exs
  apps/url_dispatcher/config/dev.exs
  apps/url_dispatcher/config/prod.exs
  apps/url_dispatcher/config/test.exs
  apps/url_dispatcher/lib/mix/tasks/omg.server.ex
  apps/url_dispatcher/lib/url_dispatcher/application.ex
  apps/url_dispatcher/mix.exs
  config/prod.exs
  mix.exs
  mix.lock
Labels: kind/refactor :gear:, p0/high, s3/review

#329 Clean up dialyzer issues
  .dialyzer_ignore
  .dialyzer_ignore.exs
  apps/admin_api/lib/admin_api/invites/inviter.ex
  apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/account_membership_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/admin_auth_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/admin_user_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/api_key_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/category_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/exchange_pair_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/key_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/mint_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/self_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/token_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transaction_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transaction_request_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/user_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/wallet_controller.ex
  apps/admin_api/lib/admin_api/v1/helpers/account_helper.ex
  apps/ewallet/lib/ewallet/exchange/exchange.ex
  apps/ewallet/lib/ewallet/fetchers/transaction_consumption_fetcher.ex
  apps/ewallet/lib/ewallet/fetchers/transaction_request_fetcher.ex
  apps/ewallet/lib/ewallet/fetchers/user_fetcher.ex
  apps/ewallet/lib/ewallet/fetchers/wallet_fetcher.ex
  apps/ewallet/lib/ewallet/gates/genesis_gate.ex
  apps/ewallet/lib/ewallet/gates/mint_gate.ex
  apps/ewallet/lib/ewallet/gates/transaction_consumption_confirmer_gate.ex
  apps/ewallet/lib/ewallet/gates/transaction_consumption_consumer_gate.ex
  apps/ewallet/lib/ewallet/gates/transaction_request_gate.ex
  apps/ewallet/lib/ewallet/seeders/cli_seeder.ex
  apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
  apps/ewallet/lib/ewallet/web/paginator.ex
  apps/ewallet/lib/ewallet/web/preloader.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/lib/ewallet/web/v1/event_handlers/event.ex
  apps/ewallet/lib/ewallet/web/v1/event_handlers/transaction_consumption_event_handler.ex
  apps/ewallet_api/lib/ewallet_api/v1/auth/client_auth.ex
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_consumption_controller.ex
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_request_controller.ex
  apps/ewallet_db/lib/ewallet_db/account.ex
  apps/ewallet_db/lib/ewallet_db/api_key.ex
  apps/ewallet_db/lib/ewallet_db/auth_token.ex
  apps/ewallet_db/lib/ewallet_db/category.ex
  apps/ewallet_db/lib/ewallet_db/exchange_pair.ex
  apps/ewallet_db/lib/ewallet_db/helpers/assoc.ex
  apps/ewallet_db/lib/ewallet_db/invite.ex
  apps/ewallet_db/lib/ewallet_db/key.ex
  apps/ewallet_db/lib/ewallet_db/membership_checker.ex
  apps/ewallet_db/lib/ewallet_db/transaction.ex
  apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
  apps/ewallet_db/lib/ewallet_db/transaction_request.ex
  apps/ewallet_db/lib/ewallet_db/types/external_id.ex
  apps/ewallet_db/lib/ewallet_db/user.ex
  apps/ewallet_db/lib/ewallet_db/wallet.ex
  apps/local_ledger/lib/local_ledger/cached_balance.ex
  mix.exs
  mix.lock
Labels: kind/refactor :gear:, p1/normal, s3/review

#375 Remove Salty
  apps/ewallet_db/lib/ewallet_db/vault.ex
  apps/ewallet_db/mix.exs
  apps/local_ledger_db/lib/local_ledger_db/vault.ex
  apps/local_ledger_db/mix.exs
  mix.lock
Labels: kind/refactor :gear:, p0/high, s3/review

#379 Prevent the use of disabled keys
  apps/admin_api/lib/admin_api/v1/controllers/key_controller.ex
  apps/ewallet_db/lib/ewallet_db/key.ex
  apps/ewallet_db/test/ewallet_db/key_test.exs
Labels: kind/bug :warning:, p0/high, s3/review

#380 Add test to ensure subunit_to_unit > 18 does not return 500
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/token_controller_test.exs
Labels: kind/enhancement :rocket:, p0/high, s3/review

#338 Update readme
  .github/CONTRIBUTING.md
  README.md
  apps/ewallet/priv/repo/report_minimum.exs
  assets/logo.png
  assets/provider_setup.jpg
  docs/demo.md
  docs/design/components.md
  docs/design/conventions.md
  docs/design/design.md
  docs/design/wallets.md
  docs/faq.md
  docs/guides/api_responsibilities.md
  docs/guides/entities.md
  docs/guides/ewallet_api_websockets.md
  docs/guides/guides.md
  docs/guides/transaction_request_flow.md
  docs/guides/usage.md
  docs/setup/advanced/api_specs.md
  docs/setup/advanced/clustering.md
  docs/setup/advanced/env.md
  docs/setup/bare_metal.md
  docs/setup/docker.md
  docs/setup/upgrading/20180619-encryption-upgrade.md
  docs/setup/vagrant.md
  docs/tests/e2e.md
  docs/tests/tests.md
  mix.exs
Labels: kind/refactor :gear:, p1/normal, s3/review

#382 Fix unknown --no-watch option error
  apps/url_dispatcher/lib/mix/tasks/omg.server.ex
Labels: kind/bug :warning:, p1/normal, s3/review

#385 Add test database setup to bare-metal readme & explanation on bash parentheses
  docs/setup/bare_metal.md
Labels: kind/bug :warning:, p1/normal, s2/wip :construction:

#376 Refactoring and fix Ui issue
  apps/admin_panel/assets/src/app/globalStyle.css
  apps/admin_panel/assets/src/app/routes/index.js
  apps/admin_panel/assets/src/omg-alert/index.js
  apps/admin_panel/assets/src/omg-app-layout/SideNavigation.js
  apps/admin_panel/assets/src/omg-consumption-panel/index.js
  apps/admin_panel/assets/src/omg-copy/index.js
  apps/admin_panel/assets/src/omg-create-account-modal/ChooseCategoryStage.js
  apps/admin_panel/assets/src/omg-create-account-modal/index.js
  apps/admin_panel/assets/src/omg-create-token-modal/index.js
  apps/admin_panel/assets/src/omg-create-transaction-modal/index.js
  apps/admin_panel/assets/src/omg-create-transaction-request-modal/index.js
  apps/admin_panel/assets/src/omg-createNewPassword-form/index.js
  apps/admin_panel/assets/src/omg-exchange-rate-modal/index.js
  apps/admin_panel/assets/src/omg-forgetPassword-form/index.js
  apps/admin_panel/assets/src/omg-invite-form/index.js
  apps/admin_panel/assets/src/omg-links/index.js
  apps/admin_panel/assets/src/omg-login-form/index.js
  apps/admin_panel/assets/src/omg-mint-token-modal/index.js
  apps/admin_panel/assets/src/omg-modal/index.js
  apps/admin_panel/assets/src/omg-page-account-detail/index.js
  apps/admin_panel/assets/src/omg-page-account/index.js
  apps/admin_panel/assets/src/omg-page-api/index.js
  apps/admin_panel/assets/src/omg-page-consumption/index.js
  apps/admin_panel/assets/src/omg-page-dashboard/index.js
  apps/admin_panel/assets/src/omg-page-detail-layout/DetailLayout.js
  apps/admin_panel/assets/src/omg-page-detail-layout/DetailSection.js
  apps/admin_panel/assets/src/omg-page-layout/SearchGroup.js
  apps/admin_panel/assets/src/omg-page-layout/TopNavigation.js
  apps/admin_panel/assets/src/omg-page-token-detail/HistoryTable.js
  apps/admin_panel/assets/src/omg-page-token-detail/index.js
  apps/admin_panel/assets/src/omg-page-token/index.js
  apps/admin_panel/assets/src/omg-page-transaction-request/index.js
  apps/admin_panel/assets/src/omg-page-transaction/index.js
  apps/admin_panel/assets/src/omg-page-user-detail/index.js
  apps/admin_panel/assets/src/omg-page-users/index.js
  apps/admin_panel/assets/src/omg-page-wallet-detail/index.js
  apps/admin_panel/assets/src/omg-page-wallets/index.js
  apps/admin_panel/assets/src/omg-token/reducer.js
  apps/admin_panel/assets/src/omg-transaction-panel/index.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/ConsumeBox.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/PropertiesTab.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/index.js
  apps/admin_panel/assets/src/omg-uikit/error/index.js
  apps/admin_panel/assets/src/omg-uikit/input/index.js
  apps/admin_panel/assets/src/omg-uikit/loading/index.js
  apps/admin_panel/assets/src/omg-uikit/select/index.js
  apps/admin_panel/assets/src/omg-users/action.js
  apps/admin_panel/assets/src/omg-users/reducer.js
  apps/admin_panel/assets/src/omg-wallet-select/index.js
  apps/admin_panel/assets/src/omg-wallet/action.js
  apps/admin_panel/assets/src/omg-wallet/walletProvider.js
  apps/admin_panel/assets/src/services/tokenService.js
  apps/admin_panel/assets/src/services/walletService.js
  apps/admin_panel/assets/src/utils/createFetcher.js
  apps/admin_panel/assets/src/utils/formatter.js
  apps/admin_panel/assets/src/utils/formatter.test.js
Labels: kind/bug :warning:, kind/enhancement :rocket:, kind/refactor :gear:, p1/normal, s3/review

#389 fix bugs link typo and cache
  apps/admin_panel/assets/src/omg-page-wallet-detail/index.js
  apps/admin_panel/assets/src/omg-transaction-panel/index.js
Labels: s2/wip :construction:
