Repository omisego/ewallet, pull requests merged in 2018-04, with the labels that each got.

#136 Remove logger from all config except containing app
  apps/admin_api/config/config.exs
  apps/admin_api/config/dev.exs
  apps/admin_panel/config/config.exs
  apps/admin_panel/config/dev.exs
  apps/ewallet/config/config.exs
  apps/ewallet/lib/ewallet/web/v1/event_handlers/event.ex
  apps/ewallet_api/config/config.exs
  apps/ewallet_db/config/test.exs
  apps/local_ledger_db/config/config.exs
  apps/local_ledger_db/config/test.exs
  config/prod.exs
Labels: enhancement :rocket:

#132 Add SENDER_EMAIL to env docs
  docs/setup/env.md
Labels: bug :warning:

#138 Fix ewallet seed error trying to insert multiple-level accounts
  apps/ewallet/priv/repo/seeders/account.exs
Labels: bug :warning:

#134 External IDs for Account schema
  apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/account_membership_controller.ex
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/account_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/account_membership_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/self_controller_test.exs
  apps/admin_api/test/admin_api/v1/views/account_view_test.exs
  apps/ewallet/lib/ewallet/web/v1/serializers/account_serializer.ex
  apps/ewallet/test/ewallet/web/v1/serializers/account_serializer_test.exs
  apps/ewallet_db/lib/ewallet_db/account.ex
  apps/ewallet_db/lib/ewallet_db/types/external_id.ex
  apps/ewallet_db/lib/ewallet_db/user.ex
  apps/ewallet_db/mix.exs
  apps/ewallet_db/priv/repo/migrations/20180329192320_add_external_id_to_account.exs
  apps/ewallet_db/test/ewallet_db/account_test.exs
  apps/ewallet_db/test/ewallet_db/types/external_id_test.exs
  apps/ewallet_db/test/ewallet_db/user_test.exs
  apps/ewallet_db/test/support/schema_case.ex
  mix.lock
Labels: enhancement :rocket:, work in progress :construction:

#140 List error codes via endpoints
  apps/admin_api/config/config.exs
  apps/admin_api/lib/admin_api/v1/error_handler.ex
  apps/admin_api/priv/spec.yaml
  apps/ewallet/lib/ewallet/web/api_docs.ex
  apps/ewallet/lib/ewallet/web/api_docs/controller.ex
  apps/ewallet/lib/ewallet/web/api_docs/errors.html.eex
  apps/ewallet/lib/ewallet/web/api_docs/errors.yaml.eex
  apps/ewallet/lib/ewallet/web/api_docs/errors_view.ex
  apps/ewallet/mix.exs
  apps/ewallet/test/ewallet/web/api_docs/controller_test.exs
  apps/ewallet/test/ewallet/web/api_docs_test.exs
  apps/ewallet_api/config/config.exs
  apps/ewallet_api/lib/ewallet_api/v1/error_handler.ex
  apps/ewallet_api/priv/spec.yaml
  mix.lock
Labels: enhancement :rocket:

#139 T167 - Swagger docs consumption
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_consumption_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_request_serializer.ex
  apps/ewallet_api/priv/spec.yaml
Labels: enhancement :rocket:

#141 Fix docker setup instructions
  README.md
Labels: bug :warning:

#146 Remove parent_id as mandatory for account creation
  apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/account_controller_test.exs
Labels: enhancement :rocket:

#144 T12 - Top level errors
  apps/admin_api/lib/admin_api/v1/error_handler.ex
  apps/admin_api/lib/admin_api/versioned_router.ex
  apps/admin_api/test/admin_api/v1/controllers/api_key_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/minted_token_controller_test.exs
  apps/admin_api/test/admin_api/v1/error_handler_test.exs
  apps/admin_api/test/admin_api/versioned_router_test.exs
  apps/ewallet/lib/ewallet/web/api_docs/errors.html.eex
  apps/ewallet/lib/ewallet/web/api_docs/errors.yaml.eex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/websocket_response_serializer.ex
  apps/ewallet/test/ewallet/gates/transaction_gate_test.exs
  apps/ewallet/test/ewallet/gates/transfer_gate_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/websocket_response_serializer_test.exs
  apps/ewallet_api/lib/ewallet_api/v1/error_handler.ex
  apps/ewallet_api/lib/ewallet_api/versioned_router.ex
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/user_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/error_handler_test.exs
  apps/ewallet_api/test/ewallet_api/versioned_router_test.exs
  apps/local_ledger/lib/local_ledger/entry.ex
  apps/local_ledger/test/local_ledger/entry_test.exs
Labels: Refactor :gear:, enhancement :rocket:

#145 Add transaction consumption current count
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_request_serializer.ex
  apps/ewallet/test/ewallet/web/v1/serializers/transaction_request_serializer_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
Labels: enhancement :rocket:

#142 Add minting token endpoints
  apps/admin_api/lib/admin_api/v1/controllers/minted_token_controller.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/minted_token_controller_test.exs
  apps/ewallet/lib/ewallet/gates/mint_gate.ex
  apps/ewallet_db/lib/ewallet_db/mint.ex
Labels: enhancement :rocket:

#148 Fix build where mix dependencies are being resolved twice
  Dockerfile
Labels: bug :warning:

#153 Update consumption event (again)
  apps/ewallet/lib/ewallet/gates/transaction_consumption_gate.ex
  apps/ewallet/lib/ewallet/gates/transaction_request_gate.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/lib/ewallet/web/v1/event_handlers/transaction_consumption_event_handler.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_consumption_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_request_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/websocket_response_serializer.ex
  apps/ewallet/test/ewallet/gates/transaction_consumption_gate_test.exs
  apps/ewallet/test/ewallet/gates/transaction_request_gate_test.exs
  apps/ewallet/test/ewallet/web/v1/event_handlers/transaction_consumption_confirmation_event_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/transaction_consumption_serializer_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/transaction_request_serializer_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/websocket_response_serializer_test.exs
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_consumption_controller.ex
  apps/ewallet_api/priv/spec.yaml
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_consumption_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
  apps/ewallet_db/lib/ewallet_db/transaction_request.ex
  apps/ewallet_db/priv/repo/migrations/20180410032138_rename_consumption_timestamp_columns.exs
  apps/ewallet_db/test/ewallet_db/transaction_consumption_test.exs
  apps/ewallet_db/test/ewallet_db/transaction_request_test.exs
Labels: Refactor :gear:, enhancement :rocket:

#154 Fix more random test failures
  apps/admin_api/test/admin_api/v1/controllers/minted_token_controller_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_controller_test.exs
Labels: bug :warning:

#151 Make Admin API Keys optional
  apps/admin_api/config/config.exs
  apps/admin_api/config/test.exs
  apps/admin_api/lib/admin_api/v1/plugs/client_auth_plug.ex
  apps/admin_api/lib/admin_api/v1/plugs/user_auth_plug.ex
  apps/admin_api/test/admin_api/v1/plugs/client_auth_plug_test.exs
  apps/admin_api/test/admin_api/v1/plugs/user_auth_plug_test.exs
Labels: enhancement :rocket:

#155 Run Quantum in global mode
  apps/ewallet_db/config/dev.exs
  apps/ewallet_db/config/prod.exs
  apps/local_ledger/config/dev.exs
  apps/local_ledger/config/prod.exs
Labels: enhancement :rocket:

#156 SearchParser supports mapped fields
  apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
  apps/ewallet/lib/ewallet/web/search_parser.ex
  apps/ewallet/test/ewallet/web/search_parser_test.exs
Labels: bug :warning:

#158 Add `mix omg.deps` to get fullstack deps
  apps/ewallet/lib/mix/tasks/omg.deps.ex
Labels: enhancement :rocket:

#164 Preload minted token in transactions
  apps/admin_api/test/admin_api/v1/views/transaction_view_test.exs
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_serializer.ex
  apps/ewallet/test/ewallet/web/v1/serializers/transaction_serializer_test.exs
  apps/ewallet_api/test/ewallet_api/v1/views/transaction_view_test.exs
Labels: bug :warning:

#160 Fix seeds failing due to id/uuid misreference
  apps/ewallet/lib/ewallet/web/preloader.ex
  apps/ewallet/priv/repo/seeders/account.exs
  apps/ewallet/priv/repo/seeders/api_key.exs
  apps/ewallet/priv/repo/seeders/initial_api_key.exs
  apps/ewallet/priv/repo/seeders/minted_token.exs
Labels: bug :warning:

#162 Generate and serve ex_doc via /docs
  .gitignore
  Dockerfile
  README.md
  apps/url_dispatcher/lib/url_dispatcher/plug.ex
  apps/url_dispatcher/test/url_dispatcher/plug_test.exs
  assets/omgshop.png
  assets/provider_setup.jpg
  mix.exs
Labels: enhancement :rocket:

#163 Add "Support" section to README
  README.md
Labels: enhancement :rocket:

#165 Add symbol to existing minted token's IDs
  apps/ewallet_db/priv/repo/migrations/20180424131331_add_symbol_to_minted_token_id.exs
Labels: bug :warning:

#167 Ensure metadata / encrypted_metadata sent to client will never be null
  apps/ewallet/lib/ewallet/web/sort_parser.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/account_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/minted_token_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_consumption_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_request_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/user_serializer.ex
  apps/ewallet_api/test/support/conn_case.ex
  apps/ewallet_db/lib/ewallet_db/user_query.ex
  apps/ewallet_db/test/ewallet_db/account_validator_test.exs
Labels: bug :warning:

#166 Add account to auth tokens in Admin API
  apps/admin_api/lib/admin_api/v1/controllers/auth_controller.ex
  apps/admin_api/lib/admin_api/v1/error_handler.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/lib/admin_api/v1/serializers/auth_token_serializer.ex
  apps/admin_api/lib/admin_api/v1/views/auth_view.ex
  apps/admin_api/priv/spec.yaml
  apps/admin_api/test/admin_api/v1/controllers/auth_controller_test.exs
  apps/admin_api/test/admin_api/v1/serializers/auth_token_serializer_test.exs
  apps/admin_api/test/admin_api/v1/views/auth_view_test.exs
  apps/admin_api/test/support/conn_case.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet_api/lib/ewallet_api/v1/serializers/auth_token_serializer.ex
  apps/ewallet_api/test/ewallet_api/v1/serializers/auth_token_serializer_test.exs
  apps/ewallet_api/test/ewallet_api/v1/views/auth_view_test.exs
  apps/ewallet_db/lib/ewallet_db/auth_token.ex
  apps/ewallet_db/lib/ewallet_db/user.ex
  apps/ewallet_db/priv/repo/migrations/20180425050633_add_account_uuid_to_auth_token.exs
  apps/ewallet_db/test/ewallet_db/auth_token_test.exs
  apps/ewallet_db/test/support/factory.ex
Labels: enhancement :rocket:

#168 Fix error 500 when consuming request with a different minted token
  apps/ewallet/lib/ewallet/gates/transaction_consumption_gate.ex
  apps/ewallet/test/ewallet/gates/transaction_consumption_gate_test.exs
  apps/ewallet/test/ewallet/gates/transaction_request_gate_test.exs
  apps/ewallet_db/test/ewallet_db/transaction_request_test.exs
Labels: bug :warning:
