Repository omisego/ewallet, pull requests merged in 2018-03, with the labels that each got.

#95 Default search_term in swagger docs to empty strings
  apps/admin_api/priv/swagger.yaml
  apps/ewallet_api/priv/swagger.yaml
Labels: enhancement :rocket:

#96 Add maximum `per_page` value
  apps/ewallet/config/config.exs
  apps/ewallet/lib/ewallet/web/paginator.ex
  apps/ewallet/test/ewallet/web/paginator_test.exs
  docs/setup/env.md
Labels: enhancement :rocket:

#100 T65 - Prevent transactions between identical addresses
  apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
  apps/local_ledger/lib/local_ledger/entry.ex
  apps/local_ledger/lib/local_ledger/entry/validator.ex
  apps/local_ledger/lib/local_ledger/errors/same_address_error.ex
  apps/local_ledger/test/local_ledger/entry_test.exs
Labels: bug :warning:

#103 Add code coverage tooling (excoveralls)
  apps/admin_api/.gitignore
  apps/admin_api/mix.exs
  apps/admin_panel/mix.exs
  apps/ewallet/mix.exs
  apps/ewallet_api/.gitignore
  apps/ewallet_api/mix.exs
  apps/ewallet_db/.gitignore
  apps/ewallet_db/mix.exs
  apps/local_ledger/mix.exs
  apps/local_ledger_db/mix.exs
  apps/url_dispatcher/mix.exs
  mix.exs
  mix.lock
Labels: enhancement :rocket:

#101 Remove UrlDispatcher redirects and add unit tests
  .gitignore
  apps/url_dispatcher/lib/url_dispatcher/plug.ex
  apps/url_dispatcher/test/test_helper.exs
  apps/url_dispatcher/test/url_dispatcher/plug_test.exs
  public/uploads/test.txt
Labels: enhancement :rocket:

#105 Fix 500 error when assigning a user with invalid email format
  apps/admin_api/lib/admin_api/v1/controllers/account_membership_controller.ex
  apps/admin_api/lib/admin_api/v1/error_handler.ex
  apps/admin_api/test/admin_api/v1/controllers/account_membership_controller_test.exs
Labels: bug :warning:

#106 Seeder fallbacks to example.com if base_url is not set
  apps/admin_api/test/admin_api/v1/controllers/account_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_controller_test.exs
  apps/ewallet/priv/repo/report_minimum.exs
  apps/ewallet/priv/repo/report_sample.exs
  apps/ewallet_db/config/config.exs
  apps/ewallet_db/config/dev.exs
  apps/ewallet_db/config/test.exs
Labels: bug :warning:

#109 Upgrade to Elixir 1.6
  Dockerfile
  apps/ewallet/test/ewallet/web/search_parser_test.exs
  apps/ewallet_db/mix.exs
  apps/ewallet_db/test/ewallet_db/key_test.exs
  apps/ewallet_db/test/ewallet_db/minted_token_test.exs
  apps/local_ledger_db/mix.exs
  mix.exs
  mix.lock
Labels: enhancement :rocket:

#114 Fix TransactionRequest-related API spec missing base responses
  apps/ewallet_api/priv/spec.yaml
Labels: bug :warning:

#113 Customizable admin email in the seed
  apps/ewallet/priv/repo/seeder.exs
  apps/ewallet/priv/repo/seeders/initial_user.exs
Labels: enhancement :rocket:

#112 Fix docs urls in the seeder
  apps/ewallet/priv/repo/report_minimum.exs
  apps/ewallet/priv/repo/report_sample.exs
Labels: bug :warning:

#116 Update ex_machina to v2.2
  apps/ewallet_db/mix.exs
  apps/local_ledger_db/mix.exs
  mix.lock
Labels: enhancement :rocket:

#118 Update all mix dependencies
  mix.lock
Labels: enhancement :rocket:

#119 `mix omg.server --no-watch` to disable webpack watch
  apps/admin_panel/lib/admin_panel/application.ex
  apps/url_dispatcher/lib/mix/tasks/omg.server.ex
Labels: enhancement :rocket:

#120 Serve fallback message when assets are missing & API key injection
  apps/admin_panel/assets/src/omisego/config.js
  apps/admin_panel/config/config.exs
  apps/admin_panel/lib/admin_panel/controllers/page_controller.ex
  apps/admin_panel/mix.exs
  apps/admin_panel/test/admin_panel/controllers/page_controller_test.exs
  apps/admin_panel/test/admin_panel/test_assets/dist/index.html
  apps/admin_panel/test/test_helper.exs
  apps/ewallet/priv/repo/report_minimum.exs
Labels: bug :warning:

#115 Improve seeding output
  apps/ewallet/lib/ewallet/cli.ex
  apps/ewallet/priv/repo/report_minimum.exs
  apps/ewallet/priv/repo/report_sample.exs
  apps/ewallet/priv/repo/seeder.exs
  apps/ewallet/priv/repo/seeders/account.exs
  apps/ewallet/priv/repo/seeders/admin.exs
  apps/ewallet/priv/repo/seeders/api_key.exs
  apps/ewallet/priv/repo/seeders/auth_token.exs
  apps/ewallet/priv/repo/seeders/initial_account.exs
  apps/ewallet/priv/repo/seeders/initial_api_key.exs
  apps/ewallet/priv/repo/seeders/initial_role.exs
  apps/ewallet/priv/repo/seeders/initial_user.exs
  apps/ewallet/priv/repo/seeders/key.exs
  apps/ewallet/priv/repo/seeders/minted_token.exs
  apps/ewallet/priv/repo/seeders/user.exs
  apps/ewallet_db/config/config.exs
  apps/ewallet_db/lib/ewallet_db/user.ex
  apps/ewallet_db/lib/ewallet_db/validator.ex
  apps/ewallet_db/test/ewallet_db/user_test.exs
  apps/ewallet_db/test/ewallet_db/validator_test.exs
  mix.exs
Labels: enhancement :rocket:

#123 Fix transaction list has broken
  apps/admin_panel/assets/src/pages/authenticated/transactions/list/tables.js
Labels: bug :warning:

#122 Fix alert box overlap the logo on the login page
  apps/admin_panel/assets/src/components/Alerter.jsx
  apps/admin_panel/assets/src/pages/public/PublicLayout.jsx
  apps/admin_panel/assets/src/styles/components/_alert.scss
Labels: bug :warning:

#121 Fix ecto warning when running migrations
  apps/admin_panel/config/config.exs
Labels: bug :warning:

#125 Fix tests randomly failing due to DB return sequence
  apps/admin_api/test/admin_api/v1/controllers/self_controller_test.exs
  apps/ewallet/lib/ewallet/helper.ex
  apps/ewallet/test/ewallet/helper_test.exs
Labels: bug :warning:

#126 Implement account level limit
  apps/admin_api/priv/spec.yaml
  apps/ewallet_db/lib/ewallet_db/account.ex
  apps/ewallet_db/lib/ewallet_db/account_validator.ex
  apps/ewallet_db/test/ewallet_db/account_test.exs
  apps/ewallet_db/test/ewallet_db/account_validator_test.exs
Labels: enhancement :rocket:

#127 Allow pagination params to be sent as string
  apps/ewallet/lib/ewallet/web/paginator.ex
  apps/ewallet/test/ewallet/web/paginator_test.exs
Labels: enhancement :rocket:

#128 Improve insufficient funds error
  apps/admin_api/lib/admin_api/v1/error_handler.ex
  apps/ewallet/test/ewallet/gates/transaction_gate_test.exs
  apps/ewallet/test/ewallet/gates/transfer_gate_test.exs
  apps/ewallet_api/lib/ewallet_api/v1/error_handler.ex
  apps/ewallet_api/test/ewallet_api/v1/controllers/transfer_controller_test.exs
  apps/local_ledger_db/lib/local_ledger_db/errors/insufficient_funds_error.ex
Labels: enhancement :rocket:

#131 Add support for reject endpoints (for transaction consumptions)
  apps/ewallet/lib/ewallet/gates/transaction_consumption_gate.ex
  apps/ewallet/lib/ewallet/web/v1/event_handlers/event.ex
  apps/ewallet/lib/ewallet/web/v1/event_handlers/transaction_consumption_event_handler.ex
  apps/ewallet/lib/ewallet/web/v1/events/event.ex
  apps/ewallet/lib/ewallet/web/v1/events/transaction_consumption_confirmation_event.ex
  apps/ewallet/lib/ewallet/web/v1/events/transaction_consumption_request_event.ex
  apps/ewallet/test/ewallet/web/v1/event_handlers/transaction_consumption_confirmation_event_test.exs
  apps/ewallet/test/ewallet/web/v1/events/transaction_consumption_confirmation_event_test.exs
  apps/ewallet/test/ewallet/web/v1/events/transaction_consumption_request_event_test.exs
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_consumption_controller.ex
  apps/ewallet_api/lib/ewallet_api/v1/router.ex
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_consumption_controller_test.exs
Labels: enhancement :rocket:

#135 Disable check_origin for web socket Endpoint
  apps/ewallet_api/config/prod.exs
Labels: enhancement :rocket:

#133 Consumption Approve / Fail refactor
  apps/admin_api/lib/admin_api/v1/error_handler.ex
  apps/ewallet/lib/ewallet/gates/transaction_consumption_gate.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_request_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/websocket_serializer.ex
  apps/ewallet_api/lib/ewallet_api/v1/channels/account_channel.ex
  apps/ewallet_api/lib/ewallet_api/v1/channels/address_channel.ex
  apps/ewallet_api/lib/ewallet_api/v1/channels/transaction_consumption_channel.ex
  apps/ewallet_api/lib/ewallet_api/v1/channels/transaction_request_channel.ex
  apps/ewallet_api/lib/ewallet_api/v1/channels/user_channel.ex
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_consumption_controller.ex
  apps/ewallet_api/lib/ewallet_api/v1/error_handler.ex
  apps/ewallet_api/lib/ewallet_api/v1/router.ex
  apps/ewallet_api/lib/ewallet_api/v1/sockets/socket.ex
  apps/ewallet_api/test/ewallet_api/v1/channels/account_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/address_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/transaction_consumption_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/transaction_request_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/channels/user_channel_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_consumption_controller_test.exs
  apps/ewallet_api/test/support/channel_case.ex
  apps/ewallet_api/test/support/conn_case.ex
  apps/ewallet_db/config/config.exs
  apps/ewallet_db/config/dev.exs
  apps/ewallet_db/config/prod.exs
  apps/ewallet_db/lib/ewallet_db/transaction_consumption.ex
  apps/ewallet_db/lib/ewallet_db/user.ex
  apps/ewallet_db/mix.exs
Labels: Refactor :gear:
