Repository omisego/ewallet, pull requests merged in 2019-04, with the labels that each got.

#901 UI improvements
  apps/admin_panel/assets/.vscode/settings.json
  apps/admin_panel/assets/package-lock.json
  apps/admin_panel/assets/package.json
  apps/admin_panel/assets/src/omg-app-layout/SideNavigation.js
  apps/admin_panel/assets/src/omg-app-layout/index.js
  apps/admin_panel/assets/src/omg-create-account-modal/ChooseCategoryStage.js
  apps/admin_panel/assets/src/omg-create-account-modal/CreateAccountStage.js
  apps/admin_panel/assets/src/omg-create-account-modal/CreateSuccessStage.js
  apps/admin_panel/assets/src/omg-create-account-modal/index.js
  apps/admin_panel/assets/src/omg-create-token-modal/index.js
  apps/admin_panel/assets/src/omg-create-transaction-request-modal/index.js
  apps/admin_panel/assets/src/omg-exchange-rate-modal/index.js
  apps/admin_panel/assets/src/omg-invite-modal/index.js
  apps/admin_panel/assets/src/omg-links/index.js
  apps/admin_panel/assets/src/omg-mint-token-modal/index.js
  apps/admin_panel/assets/src/omg-page-account/index.js
  apps/admin_panel/assets/src/omg-page-activity-log/ActivityPanel.js
  apps/admin_panel/assets/src/omg-page-api/AdminKeySection.js
  apps/admin_panel/assets/src/omg-page-configuration/index.js
  apps/admin_panel/assets/src/omg-page-each-account/AccountLayout.js
  apps/admin_panel/assets/src/omg-page-each-account/WalletDropdownChooser.js
  apps/admin_panel/assets/src/omg-page-layout/SearchGroup.js
  apps/admin_panel/assets/src/omg-page-layout/TopNavigation.js
  apps/admin_panel/assets/src/omg-page-transaction-request/index.js
  apps/admin_panel/assets/src/omg-uikit/animation/Accordion.js
  apps/admin_panel/assets/src/omg-uikit/animation/SlideInRight.js
  apps/admin_panel/assets/src/omg-uikit/breadcrumb/index.js
  apps/admin_panel/assets/src/omg-uikit/checkbox/index.js
  apps/admin_panel/assets/src/omg-uikit/icon/index.js
  apps/admin_panel/assets/src/omg-uikit/input/index.js
  apps/admin_panel/assets/src/utils/createFetcher.js
Labels: s3/review :eyes:

#896 Validate master_account setting
  apps/admin_api/lib/admin_api/v1/controllers/configuration_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/configuration_controller_test.exs
Labels: s3/review :eyes:

#916 Add transaction request fields
  apps/admin_api/test/admin_api/v1/controllers/transaction_request_controller_test.exs
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_request_serializer.ex
  apps/ewallet/test/ewallet/web/v1/serializers/transaction_request_serializer_test.exs
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
Labels: kind/bug :warning:, s2/wip :construction:

#907 Wallet balances permission check
  apps/admin_api/lib/admin_api/v1/controllers/wallet_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/transaction_request_controller_test.exs
  apps/ewallet/lib/ewallet/permissions/bouncer/bouncers/global_bouncer.ex
  apps/ewallet/lib/ewallet/permissions/bouncer/dispatcher.ex
  apps/ewallet/lib/ewallet/policies/policy_helper.ex
  apps/ewallet/lib/ewallet/web/balance_loader.ex
  apps/ewallet/lib/ewallet/web/v1/overlays/transaction_overlay.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_consumption_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_request_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/transaction_serializer.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/wallet_serializer.ex
  apps/ewallet/test/ewallet/web/v1/serializers/wallet_serializer_test.exs
Labels: s3/review :eyes:

#917 914 dynamic import app
  apps/admin_panel/assets/package-lock.json
  apps/admin_panel/assets/package.json
  apps/admin_panel/assets/src/adminPanelApp/action.js
  apps/admin_panel/assets/src/adminPanelApp/fonts.css
  apps/admin_panel/assets/src/adminPanelApp/globalStyle.css
  apps/admin_panel/assets/src/adminPanelApp/icons.css
  apps/admin_panel/assets/src/adminPanelApp/index.js
  apps/admin_panel/assets/src/adminPanelApp/reducer.js
  apps/admin_panel/assets/src/adminPanelApp/routes/authenticatedRoute.js
  apps/admin_panel/assets/src/adminPanelApp/routes/index.js
  apps/admin_panel/assets/src/adminPanelApp/routes/loadingPage.js
  apps/admin_panel/assets/src/adminPanelApp/routes/loginRoute.js
  apps/admin_panel/assets/src/adminPanelApp/theme.js
  apps/admin_panel/assets/src/clientApp/index.js
  apps/admin_panel/assets/src/index.js
  apps/admin_panel/assets/src/omg-exchange-rate-modal/index.js
  apps/admin_panel/assets/src/reducer/index.js
  apps/admin_panel/assets/src/socket/connector.js
  apps/admin_panel/assets/src/socket/connector.test.js
  apps/admin_panel/assets/webpack/commonLoaders.js
  apps/admin_panel/assets/webpack/index.html
Labels: s3/review :eyes:

#918 Update user request password
  apps/admin_api/test/admin_api/emails/update_email_email_test.exs
  apps/admin_panel/lib/admin_panel/controllers/page_controller.ex
  apps/admin_panel/lib/admin_panel/endpoint.ex
  apps/admin_panel/lib/admin_panel/router.ex
  apps/admin_panel/test/admin_panel/controllers/page_controller_test.exs
  apps/admin_panel/test/admin_panel/test_assets/dist/index.html
  apps/ewallet/lib/ewallet/web/emails/forget_password_email.ex
  apps/ewallet/test/ewallet/emails/forget_password_email_test.exs
  apps/ewallet_api/lib/ewallet_api/v1/controllers/reset_password_controller.ex
  apps/ewallet_api/priv/spec.json
  apps/ewallet_api/priv/spec.yaml
  apps/ewallet_api/priv/swagger/user/request_bodies.yaml
  apps/ewallet_api/test/ewallet_api/v1/controllers/reset_password_controller_test.exs
  apps/url_dispatcher/lib/url_dispatcher/plug.ex
Labels: s3/review :eyes:

#924 Contributing fix copy
  .github/CONTRIBUTING.md
Labels: s2/wip :construction:

#915 New transaction request options
  apps/admin_api/test/admin_api/v1/controllers/transaction_request_controller_test.exs
  apps/admin_panel/assets/.babelrc
  apps/admin_panel/assets/package-lock.json
  apps/admin_panel/assets/package.json
  apps/admin_panel/assets/src/omg-create-transaction-request-modal/index.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/TransactionRequestDetail.js
  apps/admin_panel/assets/src/omg-transaction-request/action.js
  apps/admin_panel/assets/src/omg-transaction-request/action.test.js
  apps/admin_panel/assets/src/services/transactionRequestService.js
  apps/admin_panel/assets/src/socket/connector.test.js
  apps/ewallet/lib/ewallet/gates/transaction_request_gate.ex
  apps/ewallet/test/ewallet/web/v1/serializers/transaction_request_serializer_test.exs
Labels: s3/review :eyes:

#928 Admin users wallets wrongly generated
  apps/admin_api/test/admin_api/v1/controllers/account_membership_controller_test.exs
  apps/ewallet/lib/ewallet/web/inviter.ex
Labels: kind/bug :warning:, s3/review :eyes:

#934 Fix CI deploy
  .circleci/ci_deploy.sh
Labels: s2/wip :construction:, s3/review :eyes:

#921 Bring back create buttons
  apps/admin_panel/assets/src/adminPanelApp/routes/index.js
  apps/admin_panel/assets/src/omg-create-client-key-modal/index.js
  apps/admin_panel/assets/src/omg-create-transaction-modal/index.js
  apps/admin_panel/assets/src/omg-create-transaction-request-modal/index.js
  apps/admin_panel/assets/src/omg-invite-modal/index.js
  apps/admin_panel/assets/src/omg-page-account-setting/index.js
  apps/admin_panel/assets/src/omg-page-admins/index.js
  apps/admin_panel/assets/src/omg-page-each-account/AccountAdminSubPage.js
  apps/admin_panel/assets/src/omg-page-each-account/AccountLayout.js
  apps/admin_panel/assets/src/omg-page-each-account/AccountSettingSubPage.js
  apps/admin_panel/assets/src/omg-page-transaction-request/index.js
  apps/admin_panel/assets/src/omg-page-transaction/index.js
Labels: s3/review :eyes:

#929 masteraccount setting on configurations page
  apps/admin_panel/assets/.vscode/settings.json
  apps/admin_panel/assets/src/omg-account-select/index.js
  apps/admin_panel/assets/src/omg-account/action.js
  apps/admin_panel/assets/src/omg-account/searchField.js
  apps/admin_panel/assets/src/omg-page-configuration/index.js
  apps/admin_panel/assets/src/services/accountService.js
  apps/admin_panel/assets/src/services/configurationService.js
Labels: s3/review :eyes:

#930 Handle client reset password
  apps/admin_panel/assets/package-lock.json
  apps/admin_panel/assets/package.json
  apps/admin_panel/assets/src/clientApp/index.js
  apps/admin_panel/assets/src/clientApp/omg-client-reset-password/index.js
  apps/admin_panel/assets/src/config/index.js
  apps/admin_panel/assets/src/index.js
  apps/admin_panel/assets/src/services/apiService.js
  apps/admin_panel/assets/src/services/apiService.test.js
  apps/admin_panel/assets/src/services/clientService.js
  apps/admin_panel/assets/src/utils/device.js
  apps/admin_panel/assets/src/utils/headerGenerator.js
  apps/admin_panel/assets/src/utils/headerGenerator.test.js
  apps/admin_panel/assets/webpack/webpack.dev.config.js
  apps/admin_panel/assets/webpack/webpack.prod.config.js
Labels: s3/review :eyes:

#933 Upgrade Doc for 1.2.0
  docs/setup/upgrading/README.md
  docs/setup/upgrading/v1.2.0.md
Labels: s3/review :eyes:

#932 New membership endpoints
  apps/admin_panel/assets/src/omg-access-key/searchField.js
  apps/admin_panel/assets/src/omg-admins/searchField.js
  apps/admin_panel/assets/src/omg-page-admins/index.js
  apps/admin_panel/assets/src/omg-page-api/AdminKeySection.js
  apps/admin_panel/assets/src/omg-page-each-account/AccountAdminSubPage.js
  apps/admin_panel/assets/src/omg-page-each-account/AccountKeySubPage.js
  apps/admin_panel/assets/src/omg-page-each-account/AccountNavigationBar.js
  apps/admin_panel/assets/src/services/accountService.js
Labels: s3/review :eyes:

#935 Update categories in account settings
  apps/admin_panel/assets/src/omg-account/action.js
  apps/admin_panel/assets/src/omg-page-account-setting/index.js
  apps/admin_panel/assets/src/services/accountService.js
Labels: s3/review :eyes:

#936 updatable & deletable exchange pair
  apps/admin_api/lib/admin_api/v1/controllers/exchange_pair_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/exchange_pair_controller_test.exs
  apps/admin_panel/assets/src/omg-exchange-pair/action.js
  apps/admin_panel/assets/src/omg-exchange-pair/reducer.js
  apps/admin_panel/assets/src/omg-exchange-rate-modal/createExchangeModal.js
  apps/admin_panel/assets/src/omg-exchange-rate-modal/deleteExchangeModal.js
  apps/admin_panel/assets/src/omg-exchange-rate-modal/index.js
  apps/admin_panel/assets/src/omg-page-token-detail/index.js
  apps/admin_panel/assets/src/omg-page-token/index.js
  apps/admin_panel/assets/src/services/exchangePairService.js
  apps/ewallet/lib/ewallet/gates/exchange_pair_gate.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/exchange_pair_serializer.ex
  apps/ewallet/test/ewallet/gates/exchange_pair_gate_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/exchange_pair_serializer_test.exs
  apps/ewallet_db/lib/ewallet_db/exchange_pair.ex
  apps/ewallet_db/test/ewallet_db/exchange_pair_test.exs
Labels: s3/review :eyes:

#939 Add secondary wallets
  apps/admin_panel/assets/src/omg-create-wallet-modal/index.js
  apps/admin_panel/assets/src/omg-page-wallets/index.js
  apps/admin_panel/assets/src/omg-wallet/action.js
  apps/admin_panel/assets/src/omg-wallet/reducer.js
  apps/admin_panel/assets/src/services/walletService.js
Labels: s3/review :eyes:

#943 Add validation for field length
  apps/ewallet_config/lib/ewallet_config/stored_setting.ex
  apps/ewallet_config/test/ewallet_config/stored_setting_test.exs
  apps/ewallet_db/lib/ewallet_db/account.ex
  apps/ewallet_db/lib/ewallet_db/api_key.ex
  apps/ewallet_db/lib/ewallet_db/category.ex
  apps/ewallet_db/lib/ewallet_db/key.ex
  apps/ewallet_db/lib/ewallet_db/role.ex
  apps/ewallet_db/lib/ewallet_db/token.ex
  apps/ewallet_db/lib/ewallet_db/user.ex
  apps/ewallet_db/lib/ewallet_db/wallet.ex
  apps/ewallet_db/test/ewallet_db/account_test.exs
  apps/ewallet_db/test/ewallet_db/api_key_test.exs
  apps/ewallet_db/test/ewallet_db/category_test.exs
  apps/ewallet_db/test/ewallet_db/key_test.exs
  apps/ewallet_db/test/ewallet_db/role_test.exs
  apps/ewallet_db/test/ewallet_db/token_test.exs
  apps/ewallet_db/test/ewallet_db/user_test.exs
  apps/ewallet_db/test/ewallet_db/wallet_test.exs
  apps/ewallet_db/test/support/schema_case.ex
Labels: s2/wip :construction:

#942 create key from account
  apps/admin_api/lib/admin_api/v1/controllers/key_controller.ex
  apps/admin_panel/assets/src/omg-access-key/action.js
  apps/admin_panel/assets/src/omg-access-key/reducer.js
  apps/admin_panel/assets/src/omg-access-key/selector.js
  apps/admin_panel/assets/src/omg-account/accountKeyFetcher.js
  apps/admin_panel/assets/src/omg-account/action.js
  apps/admin_panel/assets/src/omg-cache/reducer.js
  apps/admin_panel/assets/src/omg-create-admin-key-modal/index.js
  apps/admin_panel/assets/src/omg-page-api/AdminKeySection.js
  apps/admin_panel/assets/src/omg-page-each-account/AccountKeySubPage.js
  apps/admin_panel/assets/src/services/accessKeyService.js
Labels: s3/review :eyes:

#973 Exchange pair default address
  apps/admin_api/priv/spec.json
  apps/admin_api/priv/spec.yaml
  apps/admin_api/priv/swagger/exchange_pair/request_bodies.yaml
  apps/admin_api/priv/swagger/exchange_pair/response_schemas.yaml
  apps/admin_panel/assets/src/omg-alert/reducer.js
  apps/admin_panel/assets/src/omg-exchange-pair/action.js
  apps/admin_panel/assets/src/omg-exchange-rate-modal/createExchangeModal.js
  apps/admin_panel/assets/src/services/exchangePairService.js
  apps/ewallet/lib/ewallet/fetchers/account_fetcher.ex
  apps/ewallet/lib/ewallet/fetchers/amount_fetcher.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/exchange_pair_serializer.ex
  apps/ewallet/priv/swagger/exchange_pair/schemas.yaml
  apps/ewallet/test/ewallet/fetchers/account_fetcher_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/exchange_pair_serializer_test.exs
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_controller.ex
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/exchange_pair.ex
  apps/ewallet_db/lib/ewallet_db/transaction_request.ex
  apps/ewallet_db/lib/ewallet_db/validator.ex
  apps/ewallet_db/priv/repo/migrations/20190424073003_add_exchange_address_and_allow_end_user_exchanges_to_exchange_pair.exs
  apps/ewallet_db/test/support/factory.ex
Labels: kind/enhancement :rocket:
