Repository omisego/ewallet, pull requests merged in 2019-02, with the labels that each got.

#772 Pin v1.1.x to ewallet-builder:v1.1
  .circleci/config.yml
Labels: s3/review :eyes:

#763 Fix assets path in releases
  .gitignore
  Dockerfile
  Makefile
  apps/admin_api/lib/admin_api/endpoint.ex
  apps/admin_api/lib/admin_api/v1/controllers/export_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_export_controller_test.exs
  apps/admin_panel/config/config.exs
  apps/admin_panel/config/prod.exs
  apps/admin_panel/lib/admin_panel/application.ex
  apps/admin_panel/lib/admin_panel/endpoint.ex
  apps/ewallet/lib/ewallet/adapters/adapter_helper.ex
  apps/ewallet/lib/ewallet/cli.ex
  apps/ewallet/lib/ewallet/helper.ex
  apps/ewallet/test/ewallet/adapters/adapter_helper_test.exs
  apps/ewallet/test/ewallet/helper_test.exs
  apps/ewallet/test/support/db_case.ex
  apps/ewallet_config/lib/ewallet_config/storage/local.ex
  apps/ewallet_config/test/ewallet_config/storage/local_test.exs
  apps/url_dispatcher/.gitignore
  apps/url_dispatcher/lib/mix/tasks/omg.server.ex
  apps/url_dispatcher/lib/url_dispatcher/application.ex
  apps/url_dispatcher/lib/url_dispatcher/plug.ex
  apps/url_dispatcher/priv/static/private/.gitkeep
  apps/url_dispatcher/priv/static/public/.gitkeep
  apps/url_dispatcher/priv/static/public/swagger/favicon-16x16.png
  apps/url_dispatcher/priv/static/public/swagger/favicon-32x32.png
  apps/url_dispatcher/priv/static/public/swagger/swagger-ui-bundle.js
  apps/url_dispatcher/priv/static/public/swagger/swagger-ui-standalone-preset.js
  apps/url_dispatcher/priv/static/public/swagger/swagger-ui.css
  apps/url_dispatcher/priv/static/public/swagger/swagger-ui.js
  apps/url_dispatcher/priv/static/public/swagger/theme-monokai.css
  apps/url_dispatcher/priv/static/public/uploads/test.txt
  apps/url_dispatcher/test/url_dispatcher/plug_test.exs
  apps/utils/lib/helpers/normalize.ex
  apps/utils/lib/helpers/path_resolver.ex
  apps/utils/test/utils/helpers/normalize_test.exs
  apps/utils/test/utils/helpers/path_resolver_test.exs
  config/config.exs
Labels: s2/wip :construction:

#773 Fix various `/*.get` endpoints returning error 500 when not provided with `id`
  apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/account_wallet_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/admin_user_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/category_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/exchange_pair_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/role_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/token_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transaction_consumption_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transaction_request_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/user_auth_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_wallet_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/admin_user_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/category_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/exchange_pair_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/role_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_request_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/user_auth_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/account_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/admin_user_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/category_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/exchange_pair_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/role_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/transaction_request_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/user_auth_controller_test.exs
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet_api/lib/ewallet_api/v1/controllers/transaction_request_controller.ex
  apps/ewallet_api/test/ewallet_api/v1/controllers/transaction_request_controller_test.exs
Labels: flag/needs upgrade path :hammer_and_wrench:, s3/review :eyes:

#768 Fix aws name typo
  apps/admin_panel/assets/src/omg-page-configuration/index.js
Labels: s3/review :eyes:

#777 Migrate BALANCE_CACHING_FREQUENCY to EWalletConfig
  apps/ewallet/config/config.exs
  apps/ewallet_config/config/config.exs
  apps/ewallet_config/lib/ewallet_config/loaders/balance_caching_settings_loader.ex
  apps/ewallet_config/lib/ewallet_config/setting.ex
  apps/ewallet_config/lib/ewallet_config/setting_loader.ex
  apps/ewallet_config/mix.exs
  apps/ewallet_config/test/ewallet_config/loaders/balance_caching_settings_loader_test.exs
  apps/ewallet_config/test/ewallet_config/loaders/file_storage_settings_loader_test.exs
  apps/local_ledger/config/config.exs
  apps/local_ledger/config/prod.exs
  apps/local_ledger/lib/local_ledger/config.ex
Labels: s3/review :eyes:

#778 Release v1.1.0-pre.3
  apps/activity_logger/mix.exs
  apps/admin_api/mix.exs
  apps/admin_panel/mix.exs
  apps/ewallet/config/config.exs
  apps/ewallet/mix.exs
  apps/ewallet_api/mix.exs
  apps/ewallet_config/mix.exs
  apps/ewallet_db/mix.exs
  apps/load_tester/mix.exs
  apps/local_ledger/mix.exs
  apps/local_ledger_db/mix.exs
  apps/url_dispatcher/mix.exs
  apps/utils/mix.exs
Labels: s3/review :eyes:

#780 Documentation and setup updates for v1.1
  README.md
  docker-compose.yml
  docker-gen.sh
  docs/README.md
  docs/design/README.md
  docs/guides/README.md
  docs/setup/README.md
  docs/setup/advanced/api_specs.md
  docs/setup/vagrant.md
  docs/tests/README.md
Labels: s3/review :eyes:

#782 Fix ewallet-builder tag on v1.1
  .circleci/config.yml
Labels: kind/bug :warning:, s3/review :eyes:

#785 Fix wrongly merged controller tests
  apps/admin_api/test/admin_api/v1/controllers/account_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/account_wallet_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_user_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/category_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/exchange_pair_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/role_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/transaction_consumption_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/transaction_request_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/user_auth_controller_test.exs
Labels: s3/review :eyes:

#786 Version bump 1.1.0
  apps/activity_logger/mix.exs
  apps/admin_api/mix.exs
  apps/admin_panel/mix.exs
  apps/ewallet/config/config.exs
  apps/ewallet/mix.exs
  apps/ewallet_api/mix.exs
  apps/ewallet_config/mix.exs
  apps/ewallet_db/mix.exs
  apps/load_tester/mix.exs
  apps/local_ledger/mix.exs
  apps/local_ledger_db/mix.exs
  apps/url_dispatcher/mix.exs
  apps/utils/mix.exs
  docker-gen.sh
Labels: s2/wip :construction:

#789 Update docker-gen.sh to use omisego/ewallet:stable after v1.1.0 release
  docker-gen.sh
Labels: s3/review :eyes:

#793 Always restart Goth on settings load
  apps/ewallet_config/lib/ewallet_config/config.ex
  apps/ewallet_config/lib/ewallet_config/loaders/file_storage_settings_loader.ex
Labels: s2/wip :construction:

#790 Hotfix invite page broken
  apps/admin_panel/assets/src/omg-invite-form/index.js
Labels: s3/review :eyes:

#792 Remove ability to configure NODE_NAME
  apps/ewallet_api/config/prod.exs
  docs/setup/advanced/clustering.md
  rootfs/entrypoint
Labels: s2/wip :construction:

#796 Fix settings being loaded before all settings are refreshed.
  apps/ewallet_config/lib/ewallet_config/config.ex
  apps/ewallet_config/lib/ewallet_config/loaders/file_storage_settings_loader.ex
  apps/ewallet_config/lib/ewallet_config/setting_loader.ex
Labels: s2/wip :construction:

#802 Fix Goth strange behavior
  apps/admin_api/config/config.exs
Labels: s2/wip :construction:

#799 Fix building in v1.1 due to stable image change
  Makefile
Labels: s2/wip :construction:

#807 Initial blockchain integration
  .circleci/config.yml
  .gitignore
  Makefile
  apps/blockchain/.formatter.exs
  apps/blockchain/.gitignore
  apps/blockchain/README.md
  apps/blockchain/config/config.exs
  apps/blockchain/lib/blockchain.ex
  apps/blockchain/lib/blockchain/application.ex
  apps/blockchain/lib/blockchain/backend.ex
  apps/blockchain/lib/blockchain/wallet.ex
  apps/blockchain/mix.exs
  apps/blockchain/test/blockchain/backend_test.exs
  apps/blockchain/test/blockchain/wallet_test.exs
  apps/blockchain/test/test_helper.exs
  apps/blockchain_eth/.formatter.exs
  apps/blockchain_eth/.gitignore
  apps/blockchain_eth/README.md
  apps/blockchain_eth/config/config.exs
  apps/blockchain_eth/lib/blockchain_eth.ex
  apps/blockchain_eth/lib/blockchain_eth/worker.ex
  apps/blockchain_eth/mix.exs
  apps/blockchain_eth/test/blockchain_eth/worker_test.exs
  apps/blockchain_eth/test/test_helper.exs
  apps/ewallet/mix.exs
  apps/url_dispatcher/lib/url_dispatcher/application.ex
  docker-gen.sh
  mix.lock
  rel/config.exs
Labels: s3/review :eyes:

#812 Improve configuration validation
  apps/admin_api/test/admin_api/v1/controllers/configuration_controller_test.exs
  apps/ewallet_config/config/config.exs
  apps/ewallet_config/lib/ewallet_config/setting_validator.ex
  apps/ewallet_config/priv/repo/reporters/seeds_settings.exs
Labels: kind/bug :warning:, s3/review :eyes:
