Repository omisego/ewallet, pull requests merged in 2019-05, with the labels that each got.

#978 Fix unhandled error when match_all/match_any format is incorrect
  apps/ewallet/lib/ewallet/web/filters/match_parser.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/test/ewallet/web/filters/match_parser_test.exs
  apps/ewallet/test/ewallet/web/v1/error_handler_test.exs
Labels: s2/wip :construction:

#986 Fix exception raised when the given `start_by` field is not allowed
  apps/admin_api/lib/admin_api/v1/controllers/balance_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/balance_controller_test.exs
  apps/ewallet/lib/ewallet/web/paginators/start_after_paginator.ex
  apps/ewallet/test/ewallet/web/paginators/start_after_paginator_test.exs
Labels: s2/wip :construction:

#984 Fix rate exchange bug
  apps/admin_panel/assets/package-lock.json
  apps/admin_panel/assets/src/omg-create-transaction-modal/index.js
  apps/admin_panel/assets/src/omg-exchange-rate-modal/createExchangeModal.js
  apps/admin_panel/assets/src/omg-page-account/index.js
  apps/admin_panel/assets/src/omg-page-activity-log/index.js
  apps/admin_panel/assets/src/omg-page-admins/index.js
  apps/admin_panel/assets/src/omg-page-consumption/index.js
  apps/admin_panel/assets/src/omg-page-layout/TopNavigation.js
  apps/admin_panel/assets/src/omg-page-members/index.js
  apps/admin_panel/assets/src/omg-page-token/index.js
  apps/admin_panel/assets/src/omg-page-transaction-request/index.js
  apps/admin_panel/assets/src/omg-page-transaction/index.js
  apps/admin_panel/assets/src/omg-page-users/index.js
  apps/admin_panel/assets/src/omg-page-wallets/index.js
  apps/admin_panel/assets/src/omg-uikit/input/index.js
  apps/admin_panel/assets/src/utils/formatter.js
  apps/admin_panel/assets/src/utils/formatter.test.js
Labels: location/admin panel

#1003 fix flex bug
  apps/frontend/assets/src/omg-page-activity-log/index.js
Labels: bug :warning:

#1000 Supports passing exchange pair's rate as string
  apps/admin_api/lib/admin_api/v1/controllers/exchange_pair_controller.ex
  apps/admin_api/priv/spec.json
  apps/admin_api/priv/spec.yaml
  apps/admin_api/priv/swagger/exchange_pair/request_bodies.yaml
  apps/admin_api/test/admin_api/v1/controllers/exchange_pair_controller_test.exs
  apps/ewallet/lib/ewallet/gates/exchange_pair_gate.ex
  apps/ewallet/test/ewallet/gates/exchange_pair_gate_test.exs
Labels: s2/wip :construction:

#1008 update version and fix lint (#1007)
  apps/frontend/assets/package.json
  apps/frontend/assets/src/omg-uikit/input/index.js
Labels: s2/wip :construction:

#1011 Update version for v1.2
  apps/frontend/assets/package.json
Labels: s2/wip :construction:

#1012 Update verison 1.3
  apps/frontend/assets/package.json
Labels: s2/wip :construction:

#1005 Allow consumption with different token for client if exchange pair ok
  apps/ewallet/lib/ewallet/gates/transaction_consumption_consumer_gate.ex
  apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/test/ewallet/gates/transaction_consumption_consumer_gate_test.exs
  apps/ewallet/test/ewallet/validators/transaction_consumption_validator_test.exs
Labels: s2/wip :construction:

#1015 959 fix login
  apps/frontend/assets/src/adminPanelApp/action.js
  apps/frontend/assets/src/adminPanelApp/index.js
  apps/frontend/assets/src/adminPanelApp/routes/authenticatedRoute.js
  apps/frontend/assets/src/adminPanelApp/routes/index.js
  apps/frontend/assets/src/index.js
  apps/frontend/assets/src/omg-login-form/index.js
  apps/frontend/assets/src/omg-session/reducer.js
  apps/frontend/assets/src/omg-session/selector.js
  apps/frontend/assets/src/omg-user-current/action.test.js
  apps/frontend/assets/src/reducer/index.js
  apps/frontend/assets/src/socket/connector.js
  apps/frontend/assets/src/socket/connector.test.js
Labels: bug :warning:

#1035 Update user and admin
  apps/frontend/assets/src/omg-access-key/reducer.js
  apps/frontend/assets/src/omg-admins/action.js
  apps/frontend/assets/src/omg-admins/reducer.js
  apps/frontend/assets/src/omg-alert/reducer.js
  apps/frontend/assets/src/omg-api-keys/reducer.js
  apps/frontend/assets/src/omg-member/reducer.js
  apps/frontend/assets/src/omg-page-admin-detail/index.js
  apps/frontend/assets/src/omg-page-user-detail/index.js
  apps/frontend/assets/src/omg-token/reducer.js
  apps/frontend/assets/src/omg-users/action.js
  apps/frontend/assets/src/omg-users/reducer.js
  apps/frontend/assets/src/omg-wallet/reducer.js
  apps/frontend/assets/src/services/adminService.js
  apps/frontend/assets/src/services/userService.js
Labels: location/admin panel
