Repository omisego/ewallet, pull requests merged in 2019-01, with the labels that each got.

#624 Fix test case for url
  apps/admin_panel/assets/src/socket/connector.js
  apps/admin_panel/assets/src/socket/connector.test.js
Labels: kind/bug :warning:, s2/wip :construction:

#312 Switch to Distillery in releases
  .circleci/config.yml
  .dockerignore
  .gitignore
  Dockerfile
  Jenkinsfile
  Makefile
  README.md
  apps/activity_logger/lib/activity_logger/application.ex
  apps/activity_logger/lib/activity_logger/vault.ex
  apps/activity_logger/mix.exs
  apps/activity_logger/priv/repo/migrations/20181129054318_add_test_document_table.exs
  apps/activity_logger/priv/repo/migrations/20181129055336_add_test_users.exs
  apps/admin_api/mix.exs
  apps/admin_api/test/admin_api/global/controllers/status_controller_test.exs
  apps/admin_panel/config/prod.exs
  apps/admin_panel/mix.exs
  apps/ewallet/config/config.exs
  apps/ewallet/lib/ewallet/release_tasks.ex
  apps/ewallet/lib/mix/tasks/omg.seed.ex
  apps/ewallet/mix.exs
  apps/ewallet_api/mix.exs
  apps/ewallet_api/test/ewallet_api/global/controllers/status_controller_test.exs
  apps/ewallet_config/lib/ewallet_config/application.ex
  apps/ewallet_config/lib/ewallet_config/config.ex
  apps/ewallet_config/lib/ewallet_config/loaders/file_storage_settings_loader.ex
  apps/ewallet_config/lib/ewallet_config/setting.ex
  apps/ewallet_config/lib/ewallet_config/setting_loader.ex
  apps/ewallet_config/lib/ewallet_config/vault.ex
  apps/ewallet_config/mix.exs
  apps/ewallet_config/priv/repo/reporters/seeds_settings.exs
  apps/ewallet_config/priv/repo/seeds_settings/00_setting.exs
  apps/ewallet_config/test/support/config_test_helper.ex
  apps/ewallet_db/lib/ewallet_db/application.ex
  apps/ewallet_db/lib/ewallet_db/uploaders/avatar.ex
  apps/ewallet_db/lib/ewallet_db/vault.ex
  apps/ewallet_db/mix.exs
  apps/load_tester/mix.exs
  apps/local_ledger/mix.exs
  apps/local_ledger_db/config/config.exs
  apps/local_ledger_db/lib/local_ledger_db/application.ex
  apps/local_ledger_db/lib/local_ledger_db/vault.ex
  apps/local_ledger_db/mix.exs
  apps/url_dispatcher/mix.exs
  apps/url_dispatcher/test/url_dispatcher/plug_test.exs
  apps/utils/mix.exs
  config/config.exs
  docker-compose.yml
  docker-gen.sh
  mix.exs
  mix.lock
  rel/commands/config.sh
  rel/commands/initdb.sh
  rel/commands/seed.sh
  rel/config.exs
  rel/vm.args
  rootfs/entrypoint
  update-versions.sh
Labels: kind/refactor :gear:, p0/high, s2/wip :construction:

#625 Improve exporting
  apps/admin_api/lib/admin_api/v1/controllers/transaction_controller.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/csv/transaction_serializer.ex
Labels: s2/wip :construction:

#632 Fix endpoint name for user endpoint
  apps/admin_panel/assets/src/services/userService.js
Labels: bug

#623 Increase test coverage for Settings feature
  apps/admin_api/test/admin_api/v1/views/configuration_view_test.exs
  apps/admin_api/test/admin_api/v1/views/settings_view_test.exs
  apps/ewallet/lib/ewallet/web/config.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/configuration_serializer.ex
  apps/ewallet/test/ewallet/web/config_test.exs
  apps/ewallet/test/ewallet/web/v1/serializers/configuration_serializer_test.exs
  apps/ewallet_api/test/ewallet_api/global/controllers/status_controller_test.exs
  apps/ewallet_config/lib/ewallet_config/config.ex
  apps/ewallet_config/test/ewallet_config/stored_setting_test.exs
  apps/ewallet_config/test/support/factory.ex
Labels: s3/review :eyes:

#637 631 e2e storage setup
  .circleci/config.yml
Labels: kind/enhancement :rocket:, s3/review :eyes:

#646 Move InvalidDateFormatError from EWallet.Errors to Utils.Errors
  apps/utils/lib/errors/invalid_date_format_error.ex
  apps/utils/lib/helpers/date_formatter.ex
  apps/utils/test/utils/helpers/date_formatter_test.exs
Labels: s3/review :eyes:

#650 Add Dialyzer in build steps
  .circleci/config.yml
  Makefile
  mix.exs
Labels: s2/wip :construction:

#638 Add missing `redirect_url` param for `me.update_email` doc endpoint
  apps/admin_api/priv/spec.json
  apps/admin_api/priv/spec.yaml
  apps/admin_api/priv/swagger/admin/request_bodies.yaml
Labels: kind/bug :warning:, s3/review :eyes:

#644 Fix json validation for configuration
  apps/admin_panel/assets/src/omg-page-configuration/index.js
Labels: s3/review :eyes:

#648 Fix error 500 when updating an email with an invalid email format
  apps/admin_api/lib/admin_api/v1/error_handler.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/self_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/update_email_controller_test.exs
  apps/ewallet/lib/ewallet/gates/update_email_gate.ex
  apps/ewallet_db/lib/ewallet_db/update_email_request.ex
  apps/ewallet_db/test/ewallet_db/update_email_request_test.exs
Labels: s3/review :eyes:

#629 Allow the retrieval of balances for multiple wallets from local ledger
  apps/admin_api/lib/admin_api/v1/controllers/wallet_controller.ex
  apps/ewallet/lib/ewallet/fetchers/balance_fetcher.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/wallet_serializer.ex
  apps/ewallet/test/ewallet/fetchers/balance_fetcher_test.exs
  apps/local_ledger/lib/local_ledger/cached_balance.ex
  apps/local_ledger/lib/local_ledger/wallet.ex
  apps/local_ledger/test/local_ledger/cached_balance_test.exs
  apps/local_ledger/test/local_ledger/wallet_test.exs
  apps/local_ledger_db/lib/local_ledger_db/cached_balance.ex
  apps/local_ledger_db/lib/local_ledger_db/entry.ex
  apps/local_ledger_db/lib/local_ledger_db/wallet.ex
  apps/local_ledger_db/test/local_ledger_db/cached_balance_test.exs
  apps/local_ledger_db/test/local_ledger_db/wallet_test.exs
  apps/local_ledger_db/test/support/factory.ex
Labels: kind/enhancement :rocket:, s3/review :eyes:

#642 Handle Goth supervisor properly (start/stop when needed)
  apps/admin_api/lib/admin_api/v1/controllers/account_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/self_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/transaction_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/self_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_export_controller_test.exs
  apps/ewallet/lib/ewallet/adapters/adapter_helper.ex
  apps/ewallet/lib/ewallet/exporters/adapters/gcs_adapter.ex
  apps/ewallet/lib/ewallet/exporters/adapters/local_adapter.ex
  apps/ewallet/lib/ewallet/exporters/adapters/s3_adapter.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/test/ewallet/adapters/adapter_helper_test.exs
  apps/ewallet_config/lib/ewallet_config/application.ex
  apps/ewallet_config/lib/ewallet_config/config.ex
  apps/ewallet_config/lib/ewallet_config/file_storage_supervisor.ex
  apps/ewallet_config/lib/ewallet_config/loaders/file_storage_settings_loader.ex
  apps/ewallet_config/lib/ewallet_config/setting_loader.ex
  apps/ewallet_config/test/ewallet_config/file_storage_supervisor_test.exs
  apps/ewallet_config/test/ewallet_config/loaders/file_storage_settings_loader_test.exs
  apps/ewallet_db/lib/ewallet_db/application.ex
Labels: kind/bug :warning:, s3/review :eyes:

#654 Fix a race condition while testing for simultaneous transfers on an insufficient fund
  apps/admin_api/priv/swagger/user/request_bodies.yaml
  apps/local_ledger/test/local_ledger/transaction_test.exs
Labels: s3/review :eyes:

#658 Exclude soft-deleted API keys from /api_key.all
  apps/admin_api/lib/admin_api/v1/controllers/api_key_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/key_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/api_key_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/key_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/api_key_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/key_controller_test.exs
  apps/ewallet_db/lib/ewallet_db/api_key.ex
  apps/ewallet_db/lib/ewallet_db/key.ex
  apps/ewallet_db/test/ewallet_db/api_key_test.exs
Labels: s3/review :eyes:

#659 Improve Slack notifications
  .circleci/config.yml
Labels: s3/review :eyes:

#656 Refactor URL Dispatcher and server tasks
  apps/admin_api/lib/admin_api/application.ex
  apps/admin_panel/config/config.exs
  apps/admin_panel/config/dev.exs
  apps/admin_panel/config/prod.exs
  apps/admin_panel/lib/admin_panel/application.ex
  apps/ewallet/lib/ewallet/helper.ex
  apps/ewallet/test/ewallet/helper_test.exs
  apps/ewallet_api/lib/ewallet_api/application.ex
  apps/url_dispatcher/config/config.exs
  apps/url_dispatcher/config/prod.exs
  apps/url_dispatcher/lib/mix/tasks/omg.server.ex
  apps/url_dispatcher/lib/url_dispatcher/application.ex
  apps/url_dispatcher/lib/url_dispatcher/socket_dispatcher.ex
  rel/commands/initdb.sh
  rootfs/entrypoint
Labels: s2/wip :construction:

#662 Update stale documentation
  docs/design/components.md
  docs/faq.md
  docs/guides/transaction_request_flow.md
  docs/tests/tests.md
Labels: s3/review :eyes:

#663 Better handling for export failures
  apps/admin_api/config/config.exs
  apps/admin_api/lib/admin_api/v1/controllers/export_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/export_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/transaction_export_controller_test.exs
  apps/ewallet/lib/ewallet/adapters/adapter_helper.ex
  apps/ewallet/lib/ewallet/exporters/adapters/gcs_adapter.ex
  apps/ewallet/lib/ewallet/exporters/adapters/s3_adapter.ex
  apps/ewallet/lib/ewallet/exporters/csv_exporter.ex
  apps/ewallet/lib/ewallet/web/v1/error_handler.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/export_serializer.ex
  apps/ewallet/test/ewallet/web/v1/serializers/export_serializer_test.exs
  apps/ewallet_db/lib/ewallet_db/export.ex
  apps/ewallet_db/priv/repo/migrations/20190116091002_add_full_error_to_exports.exs
  apps/ewallet_db/test/ewallet_db/export_test.exs
Labels: s3/review :eyes:

#665 Refactor config command to prevent double-argv parsing
  apps/ewallet/lib/ewallet/release_tasks.ex
  docker-gen.sh
  rel/commands/config.sh
  rel/commands/initdb.sh
  rel/commands/seed.sh
  rootfs/entrypoint
  update-versions.sh
Labels: s3/review :eyes:

#671 Minor Improve content grammar and bug fixes
  apps/admin_panel/assets/src/omg-account-current/currentAccountProvider.js
  apps/admin_panel/assets/src/omg-app-layout/SideNavigation.js
  apps/admin_panel/assets/src/omg-login-form/index.js
  apps/admin_panel/assets/src/omg-page-account-setting/index.js
  apps/admin_panel/assets/src/omg-page-account/index.js
  apps/admin_panel/assets/src/omg-page-activity-log/index.js
  apps/admin_panel/assets/src/omg-page-configuration/index.js
  apps/admin_panel/assets/src/omg-page-token/index.js
  apps/admin_panel/assets/src/omg-page-transaction/index.js
  apps/admin_panel/assets/src/omg-uikit/table/index.js
  apps/admin_panel/assets/src/omg-user-current/currentUserProvider.js
Labels: s2/wip :construction:

#679 Better wallet endpoints and retrieval in the admin panel
  apps/admin_api/lib/admin_api/v1/controllers/account_wallet_controller.ex
  apps/admin_api/lib/admin_api/v1/controllers/wallet_controller.ex
  apps/admin_api/lib/admin_api/v1/router.ex
  apps/admin_api/lib/admin_api/v1/views/account_wallet_view.ex
  apps/admin_api/priv/spec.json
  apps/admin_api/priv/spec.yaml
  apps/admin_api/priv/swagger/account/paths.yaml
  apps/admin_api/priv/swagger/swagger.yaml
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/account_wallet_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/admin_auth/wallet_controller_test.exs
  apps/admin_api/test/admin_api/v1/controllers/provider_auth/wallet_controller_test.exs
  apps/admin_panel/assets/src/omg-create-transaction-modal/index.js
  apps/admin_panel/assets/src/omg-page-wallets/index.js
  apps/admin_panel/assets/src/omg-wallet/accountUsersWalletsFetcher.js
  apps/admin_panel/assets/src/omg-wallet/action.js
  apps/admin_panel/assets/src/omg-wallet/action.test.js
  apps/admin_panel/assets/src/omg-wallet/searchField.js
  apps/admin_panel/assets/src/services/walletService.js
  apps/ewallet/lib/ewallet/web/balance_loader.ex
  apps/ewallet/lib/ewallet/web/v1/serializers/wallet_serializer.ex
  apps/ewallet_db/lib/ewallet_db/wallet.ex
Labels: s3/review :eyes:

#685 Fix scroll bar jumping and minor bugs
  apps/admin_panel/assets/src/app/routes/index.js
  apps/admin_panel/assets/src/enhancer/clickOutside.js
  apps/admin_panel/assets/src/omg-account-current/currentAccountProvider.js
  apps/admin_panel/assets/src/omg-app-layout/index.js
  apps/admin_panel/assets/src/omg-create-transaction-request-modal/AdvanceCollapsable.js
  apps/admin_panel/assets/src/omg-login-form/index.js
  apps/admin_panel/assets/src/omg-login-form/reducer.js
  apps/admin_panel/assets/src/omg-member/MembersFetcher.js
  apps/admin_panel/assets/src/omg-page-token-detail/index.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/ActivityList.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/index.js
  apps/admin_panel/assets/src/omg-uikit/dropdown/withDropdownState.js
  apps/admin_panel/assets/src/omg-uikit/table/index.js
  apps/admin_panel/assets/src/omg-user-current/currentUserProvider.js
  apps/admin_panel/assets/src/reducer/index.js
Labels: s3/review :eyes:

#681 Fix match_any not returning results if the query does not match the record's association
  apps/ewallet/lib/ewallet/web/filters/match_parser.ex
Labels: s3/review :eyes:

#682 Improve originator wording
  apps/admin_panel/assets/src/omg-exchange-pair/exchangePairProvider.js
  apps/admin_panel/assets/src/omg-links/index.js
  apps/admin_panel/assets/src/omg-links/index.test.js
  apps/admin_panel/assets/src/omg-page-activity-log/ActivityPanel.js
  apps/admin_panel/assets/src/omg-page-activity-log/index.js
  apps/admin_panel/assets/src/omg-page-activity-log/searchField.js
  apps/admin_panel/assets/src/omg-page-detail-layout/DetailLayout.js
  apps/admin_panel/assets/src/omg-page-token-detail/index.js
  apps/admin_panel/assets/src/services/activityLogService.js
  apps/admin_panel/assets/src/services/walletService.js
Labels: s3/review :eyes:

#729 Fix settings
  apps/admin_api/lib/admin_api/v1/controllers/account_wallet_controller.ex
  apps/ewallet_config/lib/ewallet_config/setting.ex
  apps/ewallet_config/priv/repo/seeds_settings/00_setting.exs
  apps/ewallet_config/test/ewallet_config/setting_test.exs
  apps/local_ledger/lib/local_ledger/application.ex
Labels: kind/bug :warning:, s3/review :eyes:

#687 Fix readme for admin panel app
  apps/admin_panel/README.md
  apps/admin_panel/assets/README.md
Labels: s3/review :eyes:

#731 Fix error reporting in commands.
  rel/commands/config.sh
  rel/commands/initdb.sh
  rel/commands/seed.sh
Labels: s2/wip :construction:

#734 Fix regressed bin/ewallet command due to -* matching
  rel/commands/config.sh
  rel/commands/initdb.sh
  rel/commands/seed.sh
Labels: s2/wip :construction:

#736 Fix Slack notification mistakenly run report for mainlines
  .circleci/config.yml
Labels: s2/wip :construction:

#741 Bump version to v1.1.0-pre.2
  apps/activity_logger/mix.exs
  apps/admin_api/mix.exs
  apps/admin_panel/mix.exs
  apps/ewallet/config/config.exs
  apps/ewallet/mix.exs
  apps/ewallet_api/mix.exs
  apps/ewallet_config/mix.exs
  apps/ewallet_db/mix.exs
  apps/load_tester/mix.exs
  apps/local_ledger/mix.exs
  apps/local_ledger_db/mix.exs
  apps/url_dispatcher/mix.exs
  apps/utils/mix.exs
Labels: kind/enhancement :rocket:, s2/wip :construction:

#745 Fix documentation downloading scripts with the wrong file name
  README.md
Labels: s3/review :eyes:

#746 Fix tags building on Circle CI
  .circleci/config.yml
Labels: s2/wip :construction:

#749 Update Circle CI configuration to use versioned branch for E2E
  .circleci/config.yml
  Makefile
  README.md
  docker-bootstrap.sh
  docker-compose.yml
  docker-gen.sh
Labels: s3/review :eyes:

#738 Add reset frequency to cached balance
  apps/admin_panel/assets/src/omg-page-configuration/index.js
  apps/admin_panel/assets/src/services/configurationService.js
  apps/ewallet/config/config.exs
  apps/ewallet_config/config/config.exs
  apps/local_ledger/config/config.exs
  apps/local_ledger/lib/local_ledger/cached_balance.ex
  apps/local_ledger/test/local_ledger/cached_balance_test.exs
  apps/local_ledger_db/lib/local_ledger_db/cached_balance.ex
  apps/local_ledger_db/priv/repo/migrations/20190124042354_add_cached_cout_to_cached_balance.exs
  apps/local_ledger_db/test/local_ledger_db/cached_balance_test.exs
  docs/setup/advanced/settings.md
Labels: kind/enhancement :rocket:, s3/review :eyes:

#747 Remove sub app dependencies from ewallet sub app
  apps/admin_api/lib/admin_api/application.ex
  apps/ewallet/config/dev.exs
  apps/ewallet/config/prod.exs
  apps/ewallet/config/test.exs
  apps/ewallet/lib/ewallet.ex
  apps/ewallet/lib/ewallet/web/api_docs/controller.ex
  apps/ewallet/priv/spec.json
  apps/ewallet/priv/spec.yaml
  apps/ewallet/test/ewallet/web/api_docs/controller_test.exs
  apps/ewallet_api/lib/ewallet_api/application.ex
Labels: kind/refactor :gear:, s3/review :eyes:

#762 Fix format timezone and transaction request create bug
  apps/admin_panel/assets/src/index.js
  apps/admin_panel/assets/src/omg-consumption-panel/index.js
  apps/admin_panel/assets/src/omg-create-transaction-request-modal/index.js
  apps/admin_panel/assets/src/omg-page-account-detail/index.js
  apps/admin_panel/assets/src/omg-page-account-setting/index.js
  apps/admin_panel/assets/src/omg-page-account/index.js
  apps/admin_panel/assets/src/omg-page-activity-log/ActivityPanel.js
  apps/admin_panel/assets/src/omg-page-activity-log/index.js
  apps/admin_panel/assets/src/omg-page-api/index.js
  apps/admin_panel/assets/src/omg-page-consumption/index.js
  apps/admin_panel/assets/src/omg-page-dashboard/index.js
  apps/admin_panel/assets/src/omg-page-layout/TopNavigation.js
  apps/admin_panel/assets/src/omg-page-token-detail/HistoryTable.js
  apps/admin_panel/assets/src/omg-page-token-detail/index.js
  apps/admin_panel/assets/src/omg-page-token/index.js
  apps/admin_panel/assets/src/omg-page-transaction-export/index.js
  apps/admin_panel/assets/src/omg-page-transaction-request/index.js
  apps/admin_panel/assets/src/omg-page-transaction/index.js
  apps/admin_panel/assets/src/omg-page-user-detail/index.js
  apps/admin_panel/assets/src/omg-page-users/index.js
  apps/admin_panel/assets/src/omg-page-wallet-detail/index.js
  apps/admin_panel/assets/src/omg-page-wallets/index.js
  apps/admin_panel/assets/src/omg-transaction-panel/index.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/ActivityList.js
  apps/admin_panel/assets/src/omg-transaction-request-tab/TransactionRequestDetail.js
Labels: s3/review :eyes:
