Repository omisego/ewallet, pull requests merged in 2019-09, with the labels that each got.

#1155 Prepare blockchain token minting
  apps/eth_blockchain/lib/eth_blockchain/abi_encoder.ex
  apps/eth_blockchain/lib/eth_blockchain/adapter.ex
  apps/eth_blockchain/lib/eth_blockchain/token.ex
  apps/eth_blockchain/lib/eth_blockchain/transaction.ex
  apps/eth_blockchain/test/eth_blockchain/token_test.exs
  apps/eth_blockchain/test/eth_blockchain/transaction_test.exs
  apps/eth_blockchain/test/support/dumb_adapter.ex
Labels: flag/ethereum integration, kind/enhancement :rocket:, location/backend

#1159 Refactor EthBlockchain Adapter
  apps/admin_api/lib/admin_api/global/controllers/status_controller.ex
  apps/admin_api/test/admin_api/v1/controllers/blockchain_wallet_controller_test.exs
  apps/eth_blockchain/lib/eth_blockchain/adapter.ex
  apps/eth_blockchain/lib/eth_blockchain/adapter_server.ex
  apps/eth_blockchain/lib/eth_blockchain/application.ex
  apps/eth_blockchain/lib/eth_blockchain/balance.ex
  apps/eth_blockchain/lib/eth_blockchain/block.ex
  apps/eth_blockchain/lib/eth_blockchain/childchain.ex
  apps/eth_blockchain/lib/eth_blockchain/client.ex
  apps/eth_blockchain/lib/eth_blockchain/error_handler.ex
  apps/eth_blockchain/lib/eth_blockchain/nonce.ex
  apps/eth_blockchain/lib/eth_blockchain/status.ex
  apps/eth_blockchain/lib/eth_blockchain/token.ex
  apps/eth_blockchain/lib/eth_blockchain/transaction.ex
  apps/eth_blockchain/lib/eth_blockchain/transaction_receipt.ex
  apps/eth_blockchain/test/eth_blockchain/adapter_server_test.exs
  apps/eth_blockchain/test/eth_blockchain/adapter_test.exs
  apps/eth_blockchain/test/eth_blockchain/childchain_test.exs
  apps/eth_blockchain/test/eth_blockchain/integration/fixtures.exs
  apps/eth_blockchain/test/support/dumb_tx_adapter.ex
  apps/eth_blockchain/test/support/eth_blockchain_case.ex
  apps/ewallet/test/support/db_case.ex
Labels: flag/ethereum integration, kind/refactor :gear:, location/backend

#1163 Deposit hot wallet funds into plasma
  apps/frontend/assets/src/omg-alert/reducer.js
  apps/frontend/assets/src/omg-blockchain-wallet/action.js
  apps/frontend/assets/src/omg-blockchain-wallet/reducer.js
  apps/frontend/assets/src/omg-blockchain-wallet/selector.js
  apps/frontend/assets/src/omg-cache/reducer.js
  apps/frontend/assets/src/omg-modal/ModalController.js
  apps/frontend/assets/src/omg-page-blockchain-wallet-detail/BlockchainTokensPage.js
  apps/frontend/assets/src/omg-page-blockchain-wallet-detail/HotWalletTransferChooser.js
  apps/frontend/assets/src/omg-page-blockchain-wallet-detail/TabMenu.js
  apps/frontend/assets/src/omg-page-blockchain-wallet-detail/index.js
  apps/frontend/assets/src/omg-page-blockchain-wallets/index.js
  apps/frontend/assets/src/omg-plasma-deposit-modal/index.js
  apps/frontend/assets/src/omg-transaction/CreateHotWalletTransferButton.js
  apps/frontend/assets/src/reducer/index.js
  apps/frontend/assets/src/services/blockchainWalletService.js
  apps/frontend/assets/src/utils/createActionCreator.js
Labels: location/admin panel
